/**
 * Cat Quest Service
 *
 * Generates daily "quests" from cat companions based on the learner's profile.
 * Each cat has a personality-influenced quest style and a signature exercise.
 *
 * Quest selection reads weakNotes and weakSkills from learnerProfileStore
 * and frames them through the cat's personality.
 */

import { getCatById } from '../components/Mascot/catCharacters';
import type { Skills } from '../stores/types';
import { getTodayDateString } from '../utils/time';

/** A quest generated by a cat companion */
export interface CatQuest {
  catId: string;
  catName: string;
  title: string;
  description: string;
  targetType: 'weak_note' | 'weak_skill' | 'general';
  targetValue?: string; // e.g. "F#4" for a note, "timingAccuracy" for a skill
  xpMultiplier: number; // 1.0 = normal, 1.5 = bonus
}


/** Note number to name mapping for quest descriptions */
function midiNoteName(midi: number): string {
  const noteNames = ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B'];
  const octave = Math.floor(midi / 12) - 1;
  return `${noteNames[midi % 12]}${octave}`;
}

/** Skill to readable name */
function skillLabel(skill: keyof Skills): string {
  switch (skill) {
    case 'timingAccuracy': return 'timing';
    case 'pitchAccuracy': return 'pitch accuracy';
    case 'sightReadSpeed': return 'sight reading';
    case 'chordRecognition': return 'chord recognition';
  }
}

/** Quest message templates per cat personality */
const QUEST_TEMPLATES: Record<string, {
  weakNote: (noteName: string) => { title: string; description: string };
  weakSkill: (skill: string) => { title: string; description: string };
  general: () => { title: string; description: string };
}> = {
  'mini-meowww': {
    weakNote: (n) => ({ title: `Master ${n}`, description: `Hey! Let's nail ${n} today — one note at a time, my specialty!` }),
    weakSkill: (s) => ({ title: `${s} Practice`, description: `Time to work on your ${s}! I believe in you, even if you're bigger than me.` }),
    general: () => ({ title: 'Daily Warmup', description: 'Let\'s warm up those fingers with some easy scales!' }),
  },
  'jazzy': {
    weakNote: (n) => ({ title: `Jazz Up ${n}`, description: `${n} feeling off? Let me show you how to make it groove, baby.` }),
    weakSkill: (s) => ({ title: `Smooth ${s}`, description: `Your ${s} needs some New Orleans magic. Let's get smooth.` }),
    general: () => ({ title: 'Rooftop Riff', description: 'Play something cool today — improvise like nobody\'s watching.' }),
  },
  'chonky-monke': {
    weakNote: (n) => ({ title: `SLAM ${n}`, description: `${n} won't know what hit it. Give it the Chonky treatment!` }),
    weakSkill: (s) => ({ title: `Power ${s}`, description: `${s} getting weak? Not on MY watch. Let's go BIG.` }),
    general: () => ({ title: 'Full Keyboard Smash', description: 'Today we play LOUD. Every note deserves the Belly Slam.' }),
  },
  'luna': {
    weakNote: (n) => ({ title: `Moonlit ${n}`, description: `${n} calls to you from the shadows... master it tonight.` }),
    weakSkill: (s) => ({ title: `Mysterious ${s}`, description: `The ghost in the concert hall whispers: practice your ${s}...` }),
    general: () => ({ title: 'Midnight Practice', description: 'The moon is out. Play something haunting.' }),
  },
  'biscuit': {
    weakNote: (n) => ({ title: `Cozy ${n}`, description: `Let's practice ${n} after a nice cup of tea and cookies!` }),
    weakSkill: (s) => ({ title: `Warm ${s}`, description: `Your ${s} will improve with a gentle, cozy practice session!` }),
    general: () => ({ title: 'Snack Break Scales', description: 'Play a few warm C major scales between cookie bites!' }),
  },
  'ballymakawww': {
    weakNote: (n) => ({ title: `Celtic ${n}`, description: `${n} needs the Irish treatment! Let's work it into a wee reel, so.` }),
    weakSkill: (s) => ({ title: `Trad ${s}`, description: `Your ${s} wouldn't survive a session in Cork! Let me show you how it's done.` }),
    general: () => ({ title: 'Pub Session', description: 'Play a jig, play a reel — just play from the heart and stomp your feet!' }),
  },
  'aria': {
    weakNote: (n) => ({ title: `Operatic ${n}`, description: `Darling, your ${n} needs the elegance of La Scala. Let me help.` }),
    weakSkill: (s) => ({ title: `Refined ${s}`, description: `A true artist never neglects their ${s}. Practice, darling!` }),
    general: () => ({ title: 'Vocal Warmup', description: 'Warm up with ascending scales — pretend you\'re at the opera!' }),
  },
  'tempo': {
    weakNote: (n) => ({ title: `SPEED ${n}`, description: `${n} at double speed! Can you keep up?! LET'S GOOO!` }),
    weakSkill: (s) => ({ title: `Turbo ${s}`, description: `Your ${s} is too slow! Let's crank it up to 11!` }),
    general: () => ({ title: 'Speed Run', description: 'Play everything as fast as you can. No brakes. ZOOM!' }),
  },
};

/** Default template for unknown cats */
const DEFAULT_TEMPLATE = {
  weakNote: (n: string) => ({ title: `Practice ${n}`, description: `Let's work on ${n} today!` }),
  weakSkill: (s: string) => ({ title: `Improve ${s}`, description: `Time to practice your ${s}!` }),
  general: () => ({ title: 'Daily Practice', description: 'Complete today\'s exercise to earn bonus XP!' }),
};

/**
 * Generate a daily quest for the selected cat based on the learner's weak areas.
 * Uses a deterministic seed (date + catId) so the quest stays consistent for the day.
 */
export function generateDailyQuest(
  catId: string,
  weakNotes: number[],
  weakSkills: (keyof Skills)[],
): CatQuest {
  const cat = getCatById(catId);
  const catName = cat?.name ?? 'Your Cat';
  const templates = QUEST_TEMPLATES[catId] ?? DEFAULT_TEMPLATE;

  // Use today's date as a pseudo-random seed for daily rotation
  const today = getTodayDateString();
  const seed = hashString(`${catId}-${today}`);

  let quest: { title: string; description: string };
  let targetType: CatQuest['targetType'];
  let targetValue: string | undefined;

  if (weakNotes.length > 0 && seed % 3 !== 2) {
    // 67% chance: target a weak note
    const noteIdx = seed % weakNotes.length;
    const noteName = midiNoteName(weakNotes[noteIdx]);
    quest = templates.weakNote(noteName);
    targetType = 'weak_note';
    targetValue = noteName;
  } else if (weakSkills.length > 0 && seed % 3 !== 0) {
    // Target a weak skill
    const skillIdx = seed % weakSkills.length;
    const skill = weakSkills[skillIdx];
    quest = templates.weakSkill(skillLabel(skill));
    targetType = 'weak_skill';
    targetValue = skill;
  } else {
    // General quest
    quest = templates.general();
    targetType = 'general';
  }

  return {
    catId,
    catName,
    title: quest.title,
    description: quest.description,
    targetType,
    targetValue,
    xpMultiplier: targetType === 'general' ? 1.0 : 1.5,
  };
}

/** Simple string hash for deterministic daily rotation */
function hashString(str: string): number {
  let hash = 0;
  for (let i = 0; i < str.length; i++) {
    const char = str.charCodeAt(i);
    hash = ((hash << 5) - hash) + char;
    hash = hash & hash; // Convert to 32-bit integer
  }
  return Math.abs(hash);
}
