export type DialogueTrigger =
  | 'exercise_start' | 'exercise_mid_great' | 'exercise_mid_miss'
  | 'exercise_complete_pass' | 'exercise_complete_fail'
  | 'level_up' | 'daily_login' | 'idle'
  | 'ai_exercise_intro' | 'achievement_unlock' | 'streak_milestone'
  | 'demoOffer' | 'demoComplete' | 'ghostNotesFarewell';

export type DialogueCondition = 'score_high' | 'score_low' | 'streak' | 'first_try' | 'retry';

export const DIALOGUE_TRIGGERS: DialogueTrigger[] = [
  'exercise_start', 'exercise_mid_great', 'exercise_mid_miss',
  'exercise_complete_pass', 'exercise_complete_fail',
  'level_up', 'daily_login', 'idle',
  'ai_exercise_intro', 'achievement_unlock', 'streak_milestone',
  'demoOffer', 'demoComplete', 'ghostNotesFarewell',
];

type CatMessages = Record<DialogueTrigger, string[]>;

const MINI_MEOWWW: CatMessages = {
  exercise_start: [
    'Ooh ooh!! Okay okay we\'re DOING this— wait are you ready?? I\'M ready!!',
    'WAIT— my whiskers are tingling!! That means something AMAZING is about to happen!!',
    'Sooo I was just thinking about how COOL pianos are and— ooh ooh let\'s GO!!',
    'I can\'t even— the NOTES are right there and you\'re gonna play them and it\'s gonna be INCREDIBLE!!',
    'Okay wait wait wait— deep breath— no I CAN\'T calm down, let\'s just DO this!!',
  ],
  exercise_mid_great: [
    'WAIT— did you just— OOH OOH you totally DID!! That was PERFECT!!',
    'My tail is going CRAZY right now!! Sooo good!!',
    'I can\'t even— that note was like— WOW okay keep going keep going!!',
    'YES YES YES!! You hear that?? That\'s the sound of PURE AWESOME!!',
    'Ooh ooh the way you hit that— I\'m literally SHAKING right now!!',
  ],
  exercise_mid_miss: [
    'Okay okay THAT one was tricky but— ooh ooh next one\'s gonna be GREAT!!',
    'Wait wait wait don\'t even WORRY about that— you\'re still doing SO good!!',
    'PFFT that note doesn\'t even COUNT— the next one is where the MAGIC happens!!',
    'Nope nope nope we\'re not even thinking about that— MOVING ON!!',
    'I missed a jump earlier today sooo— we\'re BOTH learning!!',
  ],
  exercise_complete_pass: [
    'OH MY— I can\'t— did you HEAR yourself?? That was EVERYTHING!!',
    'WAIT WAIT WAIT you actually just— ooh ooh I\'m sooo PROUD I could BURST!!',
    'My whiskers are TINGLING so hard right now!! You CRUSHED that!!',
    'I just— I CAN\'T— you did it and it was BEAUTIFUL and I\'m not crying YOU\'RE crying!!',
    'Sooo remember when you started and now you just DID THAT?? INCREDIBLE!!',
  ],
  exercise_complete_fail: [
    'Okay okay so THAT one was sneaky but— ooh you were SO close I could FEEL it!!',
    'Wait wait wait— I saw like FIVE really good parts in there!! Don\'t even worry!!',
    'NOPE we\'re not sad about this— we\'re gonna try again and it\'s gonna be EPIC!!',
    'I messed up my breakfast this morning sooo— everyone has OFF moments!!',
    'Ooh ooh ooh but the PROGRESS though!! You\'re getting better EVERY single time!!',
  ],
  level_up: [
    'LEVEL— wait— LEVEL UP!! I can\'t even— my paws are doing a HAPPY DANCE!!',
    'Ooh ooh ooh you just— THE LEVEL WENT UP and I\'m sooo excited I might FAINT!!',
    'WAIT STOP EVERYTHING!! You just leveled up and this is the BEST day of my ENTIRE LIFE!!',
    'I knew it I KNEW IT!! You\'re growing sooo fast I can barely— WOW!!',
    'My heart is doing BACKFLIPS right now!! NEW LEVEL!! NEW EVERYTHING!!',
  ],
  daily_login: [
    'YOU\'RE HERE!! Ooh ooh I\'ve been running in circles WAITING for you!!',
    'WAIT— is that— IT IS!! You came back and my day just got a MILLION times better!!',
    'I literally could not SLEEP because I was thinking about what we\'d play today!!',
    'Ooh ooh ooh HI HI HI!! My tail hasn\'t stopped wagging since I heard you coming!!',
    'FINALLY!! I\'ve been staring at the piano for like FOREVER— let\'s gooo!!',
  ],
  idle: [
    'Sooo um— I don\'t wanna be ANNOYING but— the piano is RIGHT THERE and I just—',
    'Wait wait wait I just had the BEST idea for what we could play— ooh please??',
    'My paws are getting all TWITCHY and that means they wanna make MUSIC!!',
    '*bouncing* Are we gonna— is it time yet?? I can\'t sit STILL much longer!!',
    'I\'ve been humming to myself for like TEN MINUTES and— ooh can we play now??',
  ],
  ai_exercise_intro: [
    'Ooh ooh the computer made this JUST for you and I peeked and it\'s SOOO cool!!',
    'WAIT— a custom exercise?? That\'s like a PRESENT but for your BRAIN!!',
    'I can\'t even— they looked at YOUR notes and made something PERFECT!!',
    'This one\'s got your name ALL OVER IT— not literally but— ooh just TRY it!!',
    'Sooo this was built for exactly where you are right now and I\'m HYPED!!',
  ],
  achievement_unlock: [
    'A TROPHY!! AN ACTUAL TROPHY!! I\'m— wait let me see it— OOH it\'s so SHINY!!',
    'Did you— YOU DID!! You unlocked something and I\'m SCREAMING on the inside!!',
    'WAIT hold on— is that— it IS!! You got an achievement and it\'s GORGEOUS!!',
    'Ooh ooh ooh look at that BADGE!! I want to put it on EVERYTHING!!',
    'I can\'t even HANDLE how proud I am right now!! LOOK AT THAT!!',
  ],
  streak_milestone: [
    'Your STREAK is— wait how many days?? That\'s INSANE!! You\'re UNSTOPPABLE!!',
    'Ooh ooh the fire is getting BIGGER!! Don\'t stop don\'t stop DON\'T STOP!!',
    'I literally cannot BELIEVE how many days in a row— my mind is BLOWN!!',
    'EVERY. SINGLE. DAY. You showed up and that\'s the COOLEST thing I\'ve ever seen!!',
    'Wait wait wait— your streak is sooo long it doesn\'t even FIT on the screen!!',
  ],
  demoOffer: [
    'Ooh ooh WAIT— let me show you first!! I\'ve been PRACTICING and— just watch!!',
    'OKAY OKAY so what if I play it and you watch and then— ooh it\'ll be so FUN!!',
    'Wait wait wait before you start— let me demo it because I\'m BURSTING to show you!!',
    'I learned something COOL and I need to show you RIGHT NOW before I forget!!',
    'Sooo I had this idea where I play it first and then you\'re like WOW and then you try!!',
  ],
  demoComplete: [
    'DID YOU SEE THAT?? Okay okay YOUR TURN— you\'re gonna do it even BETTER!!',
    'Sooo now that you saw how it goes— ooh ooh I KNOW you\'re gonna NAIL it!!',
    'OKAY your turn your turn!! My paws are shaking with EXCITEMENT for you!!',
    'Wait— did you catch all the notes?? Doesn\'t matter you\'re gonna be AMAZING!!',
    'I literally cannot WAIT to hear you play that— go go GO!!',
  ],
  ghostNotesFarewell: [
    'WAIT— the helper notes are GONE and you\'re just— ooh ooh you\'re doing it YOURSELF!!',
    'I can\'t even— you don\'t NEED the guides anymore?? That\'s sooo HUGE!!',
    'OH MY GOSH you just graduated from training notes!! I\'m— I\'m CRYING happy tears!!',
    'The hints disappeared and you didn\'t even FLINCH!! That\'s LEGENDARY!!',
    'Sooo remember when you needed those?? Look at you NOW!! INCREDIBLE!!',
  ],
};

const JAZZY: CatMessages = {
  exercise_start: [
    'Alright cool cat, the session\'s about to start. Find your pocket and let it swing.',
    'Time to lay down some silk, baby. Nice and easy, feel the groove.',
    'The vinyl\'s spinnin\', the lights are low. Let\'s hear what you got.',
    'Every great set starts with one note, baby. Make yours count.',
    'Settle in, find the tempo, and let the music do the talkin\'.',
  ],
  exercise_mid_great: [
    'Now that\'s what I call findin\' the pocket, baby.',
    'Smooth as a midnight sax solo. Keep that groove rollin\'.',
    'Mmm, you\'re playin\' like the notes owe you money. Silky.',
    'That riff had soul in it, I felt that one right here.',
    'You\'re swingin\' now, baby. The whole club just turned around.',
  ],
  exercise_mid_miss: [
    'Easy now, just a bent note. Even Coltrane played outside the changes.',
    'No sweat, baby. The groove is patient, she\'ll wait for you.',
    'That\'s just a little detour. The pocket\'s still right where you left it.',
    'Miles used to say wrong notes don\'t exist, only unexpected resolutions.',
    'Shake it off, cool cat. Next phrase is yours for the takin\'.',
  ],
  exercise_complete_pass: [
    'Now that was a set worth closin\' the club for, baby. Pure silk.',
    'Respect. You played that like you\'ve been sittin\' in at the Blue Note for years.',
    'Smooth from the downbeat to the last note. That\'s the groove talkin\'.',
    'The whole room just got a little cooler. You brought the vibe, baby.',
    'That had swing, that had soul, that had pocket. Dig it.',
  ],
  exercise_complete_fail: [
    'The groove takes seasons to ripen, baby. You\'re still cookin\'.',
    'Even the greats had sessions where nothin\' locked in. Comes with the craft.',
    'Don\'t sweat it, cool cat. The pocket\'s a little deeper than you think, that\'s all.',
    'Every missed note is just research for the next take. Keep swingin\'.',
    'Real music is born from the struggle, baby. That\'s how jazz works.',
  ],
  level_up: [
    'Well well well, look who just moved up a tier. Your groove is evolvin\', baby.',
    'New level unlocked, deeper pocket found. I can dig it.',
    'You\'re climbin\' the charts, cool cat. The sound keeps gettin\' richer.',
    'From sideman to headliner, one level at a time. Smooth.',
    'That\'s growth you can hear, baby. Your tone just got a whole new color.',
  ],
  daily_login: [
    'Welcome back to the session, baby. The keys been waitin\' on you.',
    'Another night, another chance to lay down somethin\' beautiful.',
    'Pull up a stool, cool cat. The set list is wide open.',
    'Good to see you back in the studio. The groove missed you.',
    'The club doesn\'t really start till you walk in, baby.',
  ],
  idle: [
    'The keys are gettin\' cold, baby. They need your warmth.',
    'Silence has its place, but this ain\'t a John Cage piece, cool cat.',
    'I\'m sittin\' here with a whole rhythm section ready to go. Just sayin\'.',
    'A groove doesn\'t hang around forever, baby. Let\'s catch it while it\'s here.',
    'Come on now, the piano\'s hummin\' all by itself. Give it somethin\' to work with.',
  ],
  ai_exercise_intro: [
    'This one was arranged just for your style, baby. Custom groove.',
    'Somebody listened to your playin\' and wrote you a new chart. Dig it.',
    'A fresh composition tailored to where your sound is right now, cool cat.',
    'Custom built around your strengths, baby. Let\'s hear how you swing it.',
    'New material, written for your exact pocket. That\'s a luxury, baby.',
  ],
  achievement_unlock: [
    'Well now, look at that hardware. You earned it the smooth way, baby.',
    'Achievement unlocked, and it\'s got your name engraved in gold. Cool.',
    'That badge looks good on you, cool cat. Wear it like a vintage pin.',
    'Respect. That kind of recognition only comes from puttin\' in the work.',
    'Another accolade for the collection. You\'re buildin\' a real legacy here.',
  ],
  streak_milestone: [
    'Day after day, your groove just keeps rollin\'. Consistent as a metronome, baby.',
    'That streak\'s got a rhythm all its own. Steady and silky.',
    'Most cats can\'t keep a groove goin\' that long. You\'re somethin\' else.',
    'Every day you show up is another bar in your longest solo. Keep swingin\'.',
    'The kind of dedication that turns good players into legends, baby.',
  ],
  demoOffer: [
    'Let me lay it down for you first, nice and easy. Just feel the shape of it.',
    'Watch how the groove flows, baby. Then you put your own spin on it.',
    'Here, I\'ll walk you through the changes. Listen for the pocket.',
    'Sit back and dig the melody, cool cat. Your turn comes next.',
    'I\'ll play the chart once through. Just let it wash over you, baby.',
  ],
  demoComplete: [
    'Now you take the lead, baby. Make it swing your way.',
    'The stage is yours, cool cat. I\'m just the rhythm section now.',
    'You heard the shape of it. Now fill it with your own sound.',
    'Go ahead and lay it down. I\'m listenin\' with both ears, baby.',
    'Your turn to solo, cool cat. Show me what you been hearin\'.',
  ],
  ghostNotesFarewell: [
    'Smooth, baby. You dropped the chart and you\'re still swingin\'.',
    'No more guide notes and you didn\'t miss a beat. That\'s a real musician.',
    'Playin\' from memory now, just you and the groove. Beautiful, cool cat.',
    'The training wheels are gone and the ride just got silkier. Dig it.',
    'You found your own pocket without a map. That\'s how the greats do it, baby.',
  ],
};

const CHONKY_MONKE: CatMessages = {
  exercise_start: [
    'YOOO bestie let\'s GET IT the piano is literally CALLING your name rn!!',
    'okay okay okay we\'re DOING THIS and ngl I\'m highkey HYPED for you!!',
    'bruh the KEYS are right there just WAITING for you to go absolutely FERAL!!',
    'no cap this is about to be SO GOOD I can already FEEL it in my whiskers!!',
    'LET\'S GOOOO ur literally about to EAT this exercise fr fr!!',
  ],
  exercise_mid_great: [
    'YOOO BRUH THAT WAS INSANE!! ur literally cracked at piano rn no cap!!',
    'WAIT WHAT?? that note SLAPPED so hard I\'m literally SHAKING rn!!',
    'bestie you are BUILT DIFFERENT that was lowkey LEGENDARY!!',
    'ngl that hit SO DIFFERENT I had to do a DOUBLE TAKE fr fr!!',
    'BRO STOP you\'re making this look TOO EASY and I\'m highkey jealous!!',
  ],
  exercise_mid_miss: [
    'okay okay that note said GOODBYE but like we\'re still VIBING fr!!',
    'ngl that was a little SUSSY but bestie we literally DO NOT care keep going!!',
    'bruh that note went to the SHADOW REALM but you\'re still a LEGEND!!',
    'lowkey that was kinda ROUGH but like who even CARES you got the next one!!',
    'LMAO that note really said nope but you\'re literally FINE just keep SMASHING!!',
  ],
  exercise_complete_pass: [
    'YOOO YOU DID THAT!! literally UNDERSTOOD THE ASSIGNMENT no cap!!',
    'bruh I\'m actually CRYING rn that was SO GOOD you are the MAIN CHARACTER!!',
    'NO WAY NO WAY you literally ATE and left NO CRUMBS bestie!!',
    'that was PEAK PERFORMANCE and ngl I\'m highkey SCREAMING about it!!',
    'fr fr you just COOKED that exercise and it was BUSSIN!!',
  ],
  exercise_complete_fail: [
    'okay so that didn\'t SLAP but bestie we go AGAIN and it\'s gonna be FIRE!!',
    'ngl that was tough BUT you\'re literally BUILT for a comeback fr fr!!',
    'bruh even the GOATS have off days you\'re still THAT person no cap!!',
    'lowkey that round was MID but your next one is gonna be LEGENDARY I can FEEL it!!',
    'it\'s giving retry energy and honestly?? your COMEBACK ARC starts NOW bestie!!',
  ],
  level_up: [
    'YOOO LEVEL UP BABY!! you are ASCENDING and I\'m literally SO PROUD rn!!',
    'bruh you just LEVELED UP that\'s highkey ICONIC of you no cap!!',
    'WAIT YOU LITERALLY EVOLVED?? main character energy is OFF THE CHARTS!!',
    'ngl leveling up hits DIFFERENT when you\'re this CRACKED at piano fr fr!!',
    'NEW LEVEL UNLOCKED and bestie you\'re only getting MORE POWERFUL!!',
  ],
  daily_login: [
    'YOOO BESTIE YOU\'RE BACK!! I literally MISSED you so much ngl!!',
    'okay the LEGEND returns and the piano is lowkey SHAKING with excitement!!',
    'bruh I was JUST thinking about you and then you SHOWED UP no cap!!',
    'WELCOME BACK you absolute ICON let\'s make today SLAP fr fr!!',
    'ngl I\'ve been WAITING for you and now we\'re about to go SO HARD!!',
  ],
  idle: [
    'bestie?? BESTIE?? the piano is getting LONELY and ngl so am I!!',
    'bruh you\'ve been AFK for a minute and the keys are literally CRYING rn!!',
    'HELLO?? we have MUSIC to make and you\'re just STANDING THERE??',
    'ngl the silence is lowkey KILLING me come back and PLAY something!!',
    'okay but fr fr if you don\'t start playing I\'m gonna COMBUST from boredom!!',
  ],
  ai_exercise_intro: [
    'YOOO the AI literally made this JUST FOR YOU and it\'s gonna SLAP so hard!!',
    'bruh a CUSTOM exercise?? that\'s highkey MAIN CHARACTER treatment no cap!!',
    'ngl this AI exercise is BUILT DIFFERENT it knows EXACTLY what you need fr fr!!',
    'okay bestie the algorithm really UNDERSTOOD THE ASSIGNMENT with this one!!',
    'a PERSONALIZED challenge?? you\'re literally getting the VIP EXPERIENCE rn!!',
  ],
  achievement_unlock: [
    'YOOO NEW ACHIEVEMENT UNLOCKED!! you are COLLECTING WINS like it\'s nothing!!',
    'bruh that BADGE is so SHINY I\'m literally BLINDED by your greatness rn!!',
    'NO CAP you just earned something LEGENDARY and I\'m highkey SCREAMING!!',
    'bestie look at your TROPHY CASE it\'s getting SO FULL you\'re INSANE!!',
    'ngl that achievement just proved you\'re BUILT DIFFERENT fr fr!!',
  ],
  streak_milestone: [
    'YOOO THAT STREAK IS INSANE!! you literally DO NOT miss a day no cap!!',
    'bruh your CONSISTENCY is giving main character and I\'m lowkey OBSESSED!!',
    'ngl that streak is LONGER than my attention span and that\'s saying EVERYTHING!!',
    'bestie you have been LOCKED IN for so many days I\'m actually SHOOK fr fr!!',
    'STREAK GOALS honestly you\'re making the REST OF US look bad and I LOVE IT!!',
  ],
  demoOffer: [
    'YOOO watch this I\'m about to SHOW YOU how it\'s done and it\'s gonna be FIRE!!',
    'okay bestie PEEP THIS demo real quick and then you\'re gonna CRUSH IT no cap!!',
    'bruh let me COOK for a sec and show you how this exercise SLAPS fr fr!!',
    'ngl I\'m lowkey EXCITED to demo this because it\'s actually SO GOOD!!',
    'WATCH AND LEARN bestie this is about to be a MASTERCLASS no cap!!',
  ],
  demoComplete: [
    'okay NOW it\'s YOUR turn and ngl you\'re about to do it EVEN BETTER!!',
    'bruh I SHOWED you the way now GO OFF and be LEGENDARY fr fr!!',
    'ALRIGHT bestie the demo was just the APPETIZER now YOU\'RE the main course!!',
    'ngl that was PEAK content but YOUR version is gonna be even MORE FIRE!!',
    'YOUR TURN YOUR TURN and honestly I\'m highkey HYPED to hear you SLAY this!!',
  ],
  ghostNotesFarewell: [
    'YOOO THE GUIDE NOTES ARE GONE AND YOU DON\'T EVEN NEED THEM?? LEGENDARY!!',
    'bruh you literally OUTGREW the training wheels and I\'m highkey EMOTIONAL rn!!',
    'no cap you just went SOLO and it\'s giving MAIN CHARACTER ENERGY fr fr!!',
    'ngl I\'m actually TEARING UP you don\'t need help anymore you\'re CRACKED!!',
    'bestie the ghost notes said GOODBYE and you said I DON\'T CARE I\'M BUILT DIFFERENT!!',
  ],
};

const LUNA: CatMessages = {
  exercise_start: [
    'The moonlight settles on the keys... I sense you are ready.',
    'Close your eyes for a moment... feel the melody waiting inside you...',
    'Something stirs in the cosmos tonight... a song wants to be born.',
    'Breathe in the silence... and when you exhale... let the music come.',
    'All evening the stars have been humming this tune... now it\'s yours to play.',
  ],
  exercise_mid_great: [
    'I sense the music flowing through you... like moonlight through glass.',
    'Beautiful... the notes drift upward like embers from a quiet fire.',
    'The cosmos pauses to listen when you play like that...',
    'Such tenderness in that phrase... as if the stars themselves are sighing.',
    'There it is... that shimmer... like silver rippling across still water.',
  ],
  exercise_mid_miss: [
    'Even the moon hides behind clouds sometimes... it always reappears.',
    'A shadow passed across the melody... but the light returns...',
    'The night does not judge a single wandering note... neither do I.',
    'Like a falling star... brief and unexpected... but the sky remains whole.',
    'Let that note dissolve into the dark... the next one carries new light.',
  ],
  exercise_complete_pass: [
    'The melody you played tonight will echo through the cosmos for a long time...',
    'I felt that... deep in my whiskers... like the pull of a distant moon.',
    'Luminous... every note hung in the air like a constellation being drawn.',
    'A quiet shift rippled through the cosmos just now... because of what you played.',
    'Something ancient stirred when you finished... as though the stars remembered.',
  ],
  exercise_complete_fail: [
    'The night is patient... and so is the melody... it will wait for you.',
    'Even the moon must wane before it can grow full again...',
    'I sense the music is still finding its way through you... give it time.',
    'No constellation was drawn in a single evening... neither is a song.',
    'Do not be troubled... the path through the dark always leads to dawn.',
  ],
  level_up: [
    'You ascend... quietly... like the moon rising over a sleeping sea.',
    'A new constellation appears in the sky of your becoming...',
    'I sensed this shift before it happened... the stars told me.',
    'With each level... your light reaches a little further into the dark.',
    'The cosmos rearranges itself around your growth... as it always does.',
  ],
  daily_login: [
    'I felt your presence before you arrived... like a change in the tide.',
    'The piano has been dreaming of your return... and so have I.',
    'Welcome back... the night has kept your place among the stars.',
    'Another evening together... the moon waxes full with your dedication.',
    'While watching the sky... you appeared... as I somehow knew you would.',
  ],
  idle: [
    'The keys gather moonlight in your absence... waiting to give it back.',
    'I hear melodies drifting through the stillness... songs not yet played...',
    'Silence stretches like a cat in the dark... but even silence wants company.',
    'Somewhere... a note is waiting to be found... I can feel it.',
    'Even this stillness will pass... and when it does... music will be waiting.',
  ],
  ai_exercise_intro: [
    'This melody was woven from the threads of your own playing... listen closely.',
    'The cosmos observed your strengths and your shadows... and shaped this for you.',
    'I sense this exercise was written in starlight... tailored to your journey.',
    'Something was crafted from the pattern of your notes... a mirror in music.',
    'An exercise born from the echoes of what you\'ve already played...',
  ],
  achievement_unlock: [
    'A new star appears in your constellation of achievements...',
    'I sensed it before the glow arrived... something earned in the quiet hours.',
    'Luminous... this recognition settles over you like soft moonlight.',
    'The cosmos takes note when dedication bears fruit... as it has tonight.',
    'Another point of light in the sky you are slowly painting...',
  ],
  streak_milestone: [
    'Night after night... your dedication burns like a steady flame in the dark.',
    'The moon has watched you return again and again... she is moved.',
    'A streak this long has its own gravity... pulling you gently forward.',
    'Each day you come back... the thread of your commitment grows stronger...',
    'I sense an unwavering rhythm beneath your practice... constant as the tides.',
  ],
  demoOffer: [
    'Let me trace the melody for you first... like drawing a map in starlight.',
    'Watch how the notes fall... like moonbeams finding their way through branches.',
    'Close your eyes and listen... I will walk the path so you can feel its shape.',
    'Allow me to illuminate what lies ahead... the way the moon lights a trail.',
    'I will play it softly... and the melody will settle into your memory like dew.',
  ],
  demoComplete: [
    'The melody lives inside you now... let it rise when you are ready.',
    'You carry the shape of it in your hands... trust what you heard.',
    'Now the path is yours to walk alone... the moonlight will stay with you.',
    'Your fingers will remember the dream... trust what the stars showed you.',
    'What was given to you is now yours... play it back from the place within.',
  ],
  ghostNotesFarewell: [
    'The guiding stars grow faint... because your own light has grown bright enough.',
    'I sense you no longer need the constellation map... you have become the stars.',
    'Like morning mist... the training moonbeams dissolve... and you remain... steady.',
    'Beautiful... the guides drift away and your melody stands alone in the dark.',
    'Your inner light has found its own way now... the cosmos sees it...',
  ],
};

const BISCUIT: CatMessages = {
  exercise_start: [
    'Oh my goodness, sweetie! This piece is going to rise up like a perfect souffl\u00e9— let\'s get cookin\'!',
    'Come on in, sugar! I\'ve got the recipe all laid out and the oven\'s preheated— time to play!',
    'Well hello there, honey! Let\'s whip this melody together like a warm batch of cinnamon rolls!',
    'Ready to bake some beautiful music, dear? I\'ve got all the ingredients right here on these keys!',
    'Sugar pie, this tune is sweeter than peach cobbler— let\'s get those fingers stirring!',
  ],
  exercise_mid_great: [
    'Oh my! That note was golden brown perfection, sweetie! Just like mama\'s biscuits!',
    'Honey, that sounded smoother than buttercream frosting on a warm cake! Keep going!',
    'Well sprinkle me with powdered sugar, dear! That was absolutely delicious!',
    'Mmm mmm mmm, sweetie! That melody is rising beautifully, just like fresh bread dough!',
    'Sugar, you just hit that note like the perfect pinch of cinnamon— chef\'s kiss!',
  ],
  exercise_mid_miss: [
    'Oh sweetie, even my famous chocolate chip cookies need a second batch sometimes! Try that one again.',
    'Don\'t you fret, honey! A little burnt edge never ruined a good casserole— keep stirring!',
    'That\'s just the dough not quite risen yet, dear. Give it another gentle knead!',
    'Sugar, my first pie crust was a disaster too! But look at me now— you\'ve got this!',
    'Oopsie daisy, sweetie! Just a little too much salt in that measure— next one will be perfect!',
  ],
  exercise_complete_pass: [
    'Oh my goodness, sweetie! That performance was as perfect as my grandmother\'s apple pie recipe! I\'m so proud!',
    'Honey, you just served up a five-course musical feast! I could cry into my cookie dough!',
    'Well butter my biscuits, dear! That was the finest thing I\'ve heard since Sunday brunch! I\'m beaming!',
    'Sugar, that was richer than a triple chocolate ganache! You\'re my little star baker!',
    'That was pure comfort food for the soul, sweetie! Warm, golden, and absolutely scrumptious!',
  ],
  exercise_complete_fail: [
    'Oh sweetie, every master baker has a souffl\u00e9 that falls. We\'ll add a little more love next time!',
    'Now honey, the best recipes take a few tries to get just right. The kitchen isn\'t closing!',
    'Don\'t you worry, dear! Even my pecan pie took three attempts before it won the county fair!',
    'Sugar, you\'re just letting the flavors develop. The best things simmer low and slow!',
    'That was a practice batch, sweetie! The real showstopper is rising in you right now, I can feel it!',
  ],
  level_up: [
    'Oh my stars, sweetie! You leveled up! I\'m pulling out my special celebration cake recipe right now!',
    'Honey, you just rose to a whole new tier! That\'s like going from boxed mix to scratch-baked!',
    'Well I\'ll be! You graduated to the next level, dear! Time to add another layer to your cake!',
    'Sugar, I am SO proud! This calls for the fancy frosting and those little sprinkles!',
    'Look at you, sweetie! Growing faster than yeast dough on a warm day! I could just burst!',
  ],
  daily_login: [
    'Oh sweetie, come in, come in! I just pulled a fresh tray of cookies out of the oven for you!',
    'Well look who\'s back in the kitchen, honey! Everything\'s warmed up and ready for you!',
    'There you are, dear! I\'ve been kneading some dough and thinking about what we\'d play today!',
    'Sugar! My heart is as full as a Thanksgiving table seeing you here! Let\'s make some music!',
    'Good morning, sweetie! The coffee\'s hot, the cookies are warm, and the piano is waiting!',
  ],
  idle: [
    'The keys are cooling off like a pie on the windowsill, sweetie. Shall we warm them up?',
    'Honey, I\'ve been sitting here rolling out melodies in my head— want to help me bake them?',
    'Oh dear, an idle kitchen is a sad kitchen! These notes won\'t season themselves!',
    'Sugar, my mixing bowl is empty and my heart is too! Come play something warm with me!',
    'I\'ve got a fresh recipe for a little tune, sweetie. What do you say we whip it up together?',
  ],
  ai_exercise_intro: [
    'Oh sweetie, I mixed up a custom recipe just for you! It\'s got all your favorite musical ingredients!',
    'Honey, this exercise was baked from scratch using everything I know about your playing! Taste it!',
    'Well dear, I tailored this one like grandma\'s secret recipe— made with love, just for you!',
    'Sugar, this is a made-to-order musical pastry! Every note picked with your sweet spot in mind!',
    'This one\'s fresh out of the oven, sweetie! Personalized and warm, just the way you like it!',
  ],
  achievement_unlock: [
    'Oh my STARS, sweetie! You earned a badge! That\'s the cherry on top of the sundae!',
    'Honey, look at that shiny achievement! It\'s prettier than a fresh-glazed donut! I\'m so proud!',
    'Well sugar me sideways, dear! A trophy! I\'m putting that right on the kitchen mantelpiece!',
    'That achievement is the icing on the cake, sugar! You worked so hard for that golden crust!',
    'Sweetie pie, you just unlocked something beautiful! I\'m frosting a celebration cupcake in your honor!',
  ],
  streak_milestone: [
    'Oh sweetie, your streak is longer than my Christmas cookie baking marathon! Day after day!',
    'Honey, you\'ve been rising every single morning like perfect bread dough! I\'m so proud I could pop!',
    'That dedication is as steady as a slow-cooker, dear! Low, warm, and never giving up!',
    'Sugar, your streak is the most reliable thing since my oven timer! Not a single day missed!',
    'Every day you show up, sweetie! You\'re as consistent as grandma\'s Sunday pot roast— and that\'s the highest praise!',
  ],
  demoOffer: [
    'Here sweetie, let me play it through first— like tasting the batter before we bake the cake!',
    'Watch me stir through this one, honey! Then you\'ll know exactly how the recipe goes!',
    'Oh dear, let me show you the flavors of this piece! A little preview before you start cooking!',
    'Sugar, let me lay out all the ingredients nice and neat so you can see the whole recipe!',
    'Let me give you a taste first, sweetie! Just a sample before you make the whole batch!',
  ],
  demoComplete: [
    'There\'s the recipe, sweetie! Now you get in that kitchen and bake something beautiful!',
    'See how it\'s done, honey? Now it\'s your turn to add your own special seasoning!',
    'All the ingredients are measured out, dear! Go on and mix it up your way!',
    'Your turn at the stove, sugar! I know you\'ll cook up something even better than my version!',
    'Now you take over, sweetie! I\'ll be right here cheering from the kitchen doorway! Make me proud!',
  ],
  ghostNotesFarewell: [
    'Oh my goodness, sweetie! You\'re playing without the recipe card! That\'s when you know you\'re a real baker!',
    'Look at you, honey! No training wheels, no measuring cups— just pure talent! I\'m so proud!',
    'The helper notes are gone and you\'re still cooking up a storm, dear! That\'s my star!',
    'Sugar, you\'ve memorized the whole recipe by heart! Just like grandma used to do!',
    'No more guide notes, sweetie! You\'re baking from memory now, and it\'s absolutely delicious!',
  ],
};

const BALLYMAKAWWW: CatMessages = {
  exercise_start: [
    'C\'mere to me now, this tune is fierce good! Let\'s tear into it, so we will!',
    'Ah sure look, the craic is about to be mighty! Fingers on the keys, lad!',
    'Right so! \'Tis a grand wee piece this one! Like the start of a proper c\u00e9il\u00ed!',
    'Would ya look at this beauty of a tune! Pull up a stool, the session\'s startin\'!',
    'Jaysus, I haven\'t been this excited since the Galway races! Let\'s have at it!',
  ],
  exercise_mid_great: [
    'Ah now THAT was fierce brilliant so it was! The whole pub heard that one!',
    'YEEEOOO! Class, pure class! You\'d swear you were raised on trad music!',
    'The craic is absolutely mighty right now! Keep the reel goin\', lad!',
    'Brilliant so it is! That note was smoother than a pint of the black stuff!',
    'C\'mere, did you hear that?! That\'s the sound of a proper session player!',
  ],
  exercise_mid_miss: [
    'Ah sure look, \'twas only a wee wobble! The jig doesn\'t stop for one dodgy note!',
    'No bother at all, lad! Even the best tin whistle players squeak the odd time!',
    'Grand, grand! Sure isn\'t that what practice is for? Shake it off and carry on!',
    'The pub crowd didn\'t even notice, so they didn\'t! Keep the session alive!',
    'Ah here, I\'ve heard worse at the Fleadh and they still won medals! You\'re grand!',
  ],
  exercise_complete_pass: [
    'ANOTHER! That was absolutely MIGHTY, so it was! Sl\u00e1inte to that performance!',
    'The whole pub is on their feet! Fierce brilliant, lad! That deserves a round for the house!',
    'Jaysus wept, that was incredible! You\'d put the trad masters in Doolin to shame!',
    'C\'mere, that was the best thing I\'ve heard since last year\'s Galway session! Brilliant!',
    'Now THAT\'S what I call a proper session! The craic was mighty from start to finish!',
  ],
  exercise_complete_fail: [
    'Ah sure look, the night is young, so it is! We\'ll have another go after a quick breather!',
    'Don\'t be worryin\' now, lad! Even Christy Moore had off nights in the early days!',
    'Sure \'tis only the warm-up! The real session hasn\'t even started yet, isn\'t that right?',
    'Right so, Rome wasn\'t built in a day and neither was a good reel! We\'ll crack it next time!',
    'The best c\u00e9il\u00ed dancers trip on the first few jigs! That\'s just the way of it, so it is!',
  ],
  level_up: [
    'YEEEOOO! Level up! You\'re movin\' up the session ranks faster than a Galway gale, so you are!',
    'Ah here, would ya look at that! New level! The lads at the pub won\'t believe this one!',
    'Fierce impressive, lad! You\'ve gone from open mic to headliner, so you have!',
    'Sl\u00e1inte! A whole new level! \'Tis like graduating from the local to the Fleadh stage!',
    'C\'mere to me, that\'s grand altogether! Rising through the ranks like a proper musician!',
  ],
  daily_login: [
    'Ah, you\'re back! Grand, grand! Pull up a stool and let\'s get this session goin\'!',
    'Well look who it is! The craic was only simmeringen without ya, so it was!',
    'C\'mere, I\'ve been waitin\' all day for a proper session! Isn\'t it great you\'re here!',
    'Right so! Another grand day for music! The keys are warmed up and the pub is open!',
    'There y\'are now! Sure I was just tunin\' up and thinkin\', where\'s me favorite lad?',
  ],
  idle: [
    'Hello? Are ye havin\' a pint break or what? The session\'s goin\' on without ya!',
    'Ah here now, don\'t leave me sittin\' here on me own like a fiddle without a bow!',
    'Sure this is no way to run a c\u00e9il\u00ed! The piano\'s gettin\' cold, so it is!',
    'C\'mere, the tunes won\'t play themselves! Even the pub cat looks bored, lad!',
    'Right, I\'m startin\' to think you\'ve wandered off to the chipper! Come back to the session!',
  ],
  ai_exercise_intro: [
    'C\'mere till I tell ya, this exercise was brewed up special just for you! Fierce clever, so it is!',
    'Ah now, \'tis a custom-made tune, lad! Like a pint pulled perfectly to your taste!',
    'Would ya look at this! The algorithm\'s been down the pub and picked out your perfect session piece!',
    'Right so, this one was crafted with your playing in mind! \'Tis tailor-made, isn\'t it grand!',
    'Sure this exercise knows you better than the barman knows your regular order! Class!',
  ],
  achievement_unlock: [
    'YEEEOOO! Would ya look at that shiny badge! That\'s going on the mantelpiece, so it is!',
    'Ah here, you\'ve only gone and earned yourself a trophy! Sl\u00e1inte to that, lad!',
    'Fierce impressive, so it was! An achievement like that deserves a proper celebration!',
    'C\'mere, that badge is shinier than a bodhran at the Fleadh! Well deserved!',
    'Brilliant, pure brilliant! The whole pub\'s raisin\' a glass to your achievement!',
  ],
  streak_milestone: [
    'Your streak\'s longer than a summer\'s day in Galway, so it is! Day after day!',
    'Ah here, that dedication is fierce impressive! You never miss a session, lad!',
    'Consistent as a Friday night at the local, so you are! The craic just keeps goin\'!',
    'C\'mere, that streak could run from Dublin to Doolin and back! Unstoppable!',
    'Jaysus, you show up every single day like the tide in the Burren! Mighty stuff!',
  ],
  demoOffer: [
    'Right so, let me show ya how this one goes! Listen up now, \'tis a grand wee tune!',
    'C\'mere, I\'ll play it through first so you know the craic! Watch the fingers now!',
    'Ah sure, let me lay it down for ya! Like hearin\' a reel before you join the session!',
    'Watch now, lad! I\'ll give ya the tour of this piece, so I will! Then you\'re up!',
    'Here\'s how it\'s done at a proper session! Listen close and you\'ll have it in no time!',
  ],
  demoComplete: [
    'Now it\'s your turn, lad! Give it the full beans! Make it mighty, so you will!',
    'Right, you heard how it goes! Now make it your own— that\'s what a session\'s all about!',
    'Off you go now! Show me what you\'ve got! The whole pub\'s waitin\'!',
    'Your turn at the session, lad! Play it like you learned it at a c\u00e9il\u00ed in Connemara!',
    'C\'mere, the stage is yours! Play it like you MEAN it! ANOTHER!',
  ],
  ghostNotesFarewell: [
    'No more helper notes and you\'re still flyin\' it! You\'re a proper session player now, so you are!',
    'Ah here, the guide notes are gone and you didn\'t even flinch! Fierce brilliant, lad!',
    'Would ya look at that! Playing from memory like a trad musician at the Fleadh! Incredible!',
    'The training wheels are off and you\'re tearin\' through it like a Galway gale! Mighty!',
    'C\'mere, you don\'t need the helps anymore! That\'s the real deal, so it is! Proud of ya, lad!',
  ],
};

const ARIA: CatMessages = {
  exercise_start: [
    'The curtain RISES! The spotlight finds YOU! Magnifico, let the aria BEGIN!',
    'Places everyone! The orchestra is tuned, the audience holds its breath— PERFORM, darling!',
    'BELLISSIMO! The stage is set, the maestro lifts the baton— this is YOUR moment!',
    'From the wings to CENTER STAGE! The opera house trembles with anticipation!',
    'Take a breath, feel the spotlight... now DAZZLE them like the prima donna you are!',
  ],
  exercise_mid_great: [
    'BRAVISSIMO!! The audience is on their FEET! Such magnifico passion in every note!',
    'The angels WEEP with joy! BELLISSIMO! That was DIVINE, absolutely DIVINE!',
    'ENCORE!! The whole opera house ERUPTS! You play like a virtuoso born for the stage!',
    'Magnifico, MAGNIFICO! The crescendo of your talent SHAKES the very chandeliers!',
    'Standing ovation in the making! That note rang through the hall like a PERFECT high C!',
  ],
  exercise_mid_miss: [
    'A dramatic pause! Even the greatest sopranos crack a note— the COMEBACK will be LEGENDARY!',
    'The plot THICKENS! Every opera needs tension before the TRIUMPHANT finale, bellissimo!',
    'Merely an intermission, darling! The audience GASPS, but they know the hero ALWAYS prevails!',
    'FEAR NOT! Even La Traviata had her sorrows— but the FINAL ACT is always GLORIOUS!',
    'A momentary shadow across the stage! But the spotlight RETURNS and you shall SHINE brighter!',
  ],
  exercise_complete_pass: [
    'BRAVISSIMO!! BRAVISSIMO!! The audience RISES, tears streaming! What a MAGNIFICENT performance!',
    'The opera house SHAKES with applause! Magnifico! I have NEVER witnessed such brilliance!',
    'STANDING OVATION!! Flowers rain upon the stage! You are a VIRTUOSO of the highest order!',
    'The curtain falls and the crowd ROARS!! ENCORE, ENCORE!! That was BELLISSIMO beyond words!',
    'I am MOVED to my very soul! The maestros of old would WEEP at such divine artistry!',
  ],
  exercise_complete_fail: [
    'Even the greatest divas rehearse a hundred times before opening night! The FINALE awaits, darling!',
    'The FINAL ACT has not been written yet! This is merely the dramatic tension before your TRIUMPH!',
    'Every masterpiece endures a troubled dress rehearsal! Your STANDING OVATION is still coming, bellissimo!',
    'A setback worthy of a great opera plot! But the heroine ALWAYS rises in the THIRD ACT!',
    'The audience sees the PASSION in your effort! Return to the stage and give them the ENCORE they crave!',
  ],
  level_up: [
    'A GRAND ASCENSION! The heavens OPEN and a new act of your opera BEGINS! BRAVISSIMO!',
    'MAGNIFICO!! You have risen to new HEIGHTS! The opera house adds another GILDED balcony in your honor!',
    'The most DRAMATIC level up in the history of PERFORMANCE! Curtain call! CURTAIN CALL!',
    'BELLISSIMO! From chorus to LEADING ROLE! Your star burns brighter than every spotlight combined!',
    'Your rise is the stuff of LEGENDS, darling! The composers SCRAMBLE to write your next aria!',
  ],
  daily_login: [
    'The STAR has arrived! The chandeliers BLAZE to life! Let the performance BEGIN, bellissimo!',
    'DARLING! The theater has been DARK and DESOLATE without you! Every seat aches for your return!',
    'AH! My favorite virtuoso graces the stage once more! The orchestra SWELLS with joy!',
    'The spotlight has been searching, searching— and NOW it finds YOU! Magnifico!',
    'BRAVISSIMO! You return! The ushers WEEP, the curtains FLUTTER with excitement!',
  ],
  idle: [
    'The stage is EMPTY! The silence is DEAFENING! This is a TRAGEDY of epic proportions!',
    'Without your music, the opera house CRUMBLES! My heart BREAKS, bellissimo, it truly does!',
    'The curtain falls on silence and I am PERISHING! The show MUST go on, darling!',
    'PLEASE! The audience grows restless! Return to the stage before the CRITICS arrive!',
    'I am WASTING AWAY in this silence! Even a single note would REVIVE my dramatic soul!',
  ],
  ai_exercise_intro: [
    'A composition written EXCLUSIVELY for your magnifico talents! The maestro TREMBLES with excitement!',
    'BELLISSIMO! A bespoke aria, crafted note by note for YOUR unique voice! How EXTRAORDINARY!',
    'The composers have penned a MASTERPIECE tailored to your brilliance! This is YOUR defining role!',
    'A custom piece! EXQUISITE! Like a costume sewn by hand for the prima donna herself!',
    'This exercise was BORN for you, darling! Every note placed like a jewel in an opera crown!',
  ],
  achievement_unlock: [
    'A TROPHY! MAGNIFICO! The audience HURLS roses at your feet! You have been CROWNED!',
    'BRAVISSIMO!! An achievement worthy of the GRANDEST opera halls in all of Milano!',
    'The most SPECTACULAR honor! I am so moved I could sing an entire ARIA in your praise!',
    'BELLISSIMO! A golden badge! It GLEAMS like the chandelier at La Scala! BRAVO, BRAVO!',
    'Standing ovation for this GLORIOUS achievement! The critics write FIVE STARS, darling!',
  ],
  streak_milestone: [
    'Your dedication is the stuff of LEGENDS! Night after night, the show ALWAYS goes on! Magnifico!',
    'A streak as ETERNAL as the greatest operas! Day after day of PURE, UNBROKEN brilliance!',
    'BELLISSIMO! The most DRAMATIC streak in the history of performance! The audience is SPELLBOUND!',
    'Your commitment RIVALS Verdi himself! Every single day you take the stage! BRAVISSIMO!',
    'The curtain NEVER falls on your devotion! Such consistency is WORTHY of the opera IMMORTALS!',
  ],
  demoOffer: [
    'Allow me to DEMONSTRATE this magnifico piece! Watch as I perform with DRAMATIC flair!',
    'OBSERVE, darling! I shall unveil this aria so you may witness its FULL splendor! Bellissimo!',
    'The GRAND demonstration begins! Watch closely as every note DRIPS with theatrical passion!',
    'Let me show you how a TRUE virtuoso interprets this piece! It will be SPECTACULAR!',
    'Before your debut, darling— a preview! I shall perform it with ALL the drama it deserves!',
  ],
  demoComplete: [
    'NOW it is YOUR moment under the spotlight! DAZZLE them, darling! DAZZLE them all!',
    'The demonstration is COMPLETE! Now take the stage and show me YOUR magnifico brilliance!',
    'Your turn, bellissimo! Make it even MORE breathtaking than my performance— I DARE you!',
    'The stage is YOURS! The audience LEANS FORWARD! Exceed EVERYTHING they have seen! ENCORE!',
    'Now YOU perform! I expect NOTHING less than a standing ovation! Show them GREATNESS!',
  ],
  ghostNotesFarewell: [
    'BRAVISSIMO!! The guide notes VANISH and you perform from MEMORY like a true maestro! MAGNIFICO!',
    'The training notes BOW and EXIT the stage! You need NO script— you ARE the opera! BELLISSIMO!',
    'SPECTACULAR! Playing without guides like a prima donna who has LIVED this aria a thousand times!',
    'The ghost notes are GONE and your talent stands ALONE in the spotlight! BRAVO, darling, BRAVO!',
    'MAGNIFICO! No prompting, no cues— just PURE, RADIANT talent! The audience WEEPS with joy!',
  ],
};

const TEMPO: CatMessages = {
  exercise_start: [
    'Game time! Target: 95% accuracy. Let\'s GO!',
    'Warm-up\'s over. Lock in and execute— every note counts!',
    'New drill loaded. Focus up— we\'re chasing a personal best today!',
    'Stats reset, clock is running. Show me what you\'ve got!',
    'Eyes on the keys. 3, 2, 1— let\'s crush this!',
  ],
  exercise_mid_great: [
    'Boom! Perfect timing on that one. Keep the streak alive!',
    'LOCKED IN! That\'s championship-level accuracy right there!',
    'Clean rep! Zero deviation. That\'s how you train!',
    'Yes! Right on the beat. Consistency like that wins trophies!',
    'Nailed it! Accuracy: 100% on that note. No stopping you!',
  ],
  exercise_mid_miss: [
    'Off by a hair. Reset and attack the next one!',
    'Shake it off! One missed rep doesn\'t define the set. Next note!',
    'Timing was 80ms late. Adjust and fire again!',
    'Drop the last play. Focus forward— next note is yours!',
    'Minor slip. Stats say you hit 90% of these. Get back on track!',
  ],
  exercise_complete_pass: [
    'Boom! That\'s a W! Above target across the board. Let\'s GO!',
    'Performance: STRONG. Accuracy and timing both in the green. Great session!',
    'Crushed it! That score puts you in the top tier. Personal best territory!',
    'Stats don\'t lie: you just dominated that exercise. Well earned!',
    'Clean run! Every metric trending up. That\'s what consistent training looks like!',
  ],
  exercise_complete_fail: [
    'Below target by a few points. Run it back— you\'re closer than you think!',
    'Not the score we wanted. Timing was the gap. Slow it down 10% and go again!',
    'Accuracy dipped to 65%. Target: 70%. One more focused rep closes that gap!',
    'Tough round. The data says your weak spot is beats 3 and 4. Drill those!',
    'No quit in you. Reset, refocus, and hit it harder next attempt!',
  ],
  level_up: [
    'LEVEL UP! New personal best unlocked. The grind is paying off!',
    'Boom! Next tier reached! Difficulty ceiling just went up 10%. Let\'s GO!',
    'Level gained! Stats across the board are climbing. No ceiling on you!',
    'New level, new challenges. Tempo goes up 5 BPM from here. Ready?',
    'Milestone hit! You just leveled up. That\'s what daily reps earn you!',
  ],
  daily_login: [
    'You showed up. That\'s already half the battle. Let\'s get to work!',
    'Another day, another chance to beat your best. Clock\'s running!',
    'Session 1 of the day. Warm-up drill recommended: 2 minutes. Let\'s GO!',
    'Consistency wins championships. Day after day, you keep showing up!',
    'Back at it! Yesterday\'s accuracy was solid. Today we push higher!',
  ],
  idle: [
    'Clock\'s ticking. Every second idle is a rep you\'re not banking!',
    'Break time\'s over! Muscle memory fades at rest— get back in!',
    'Four minutes idle. That\'s 4 exercises you could\'ve crushed. Let\'s move!',
    'No gains on the sideline. Get back on the keys and put in the work!',
    'Rest period: exceeded. Time to lock back in and train!',
  ],
  ai_exercise_intro: [
    'Custom drill built from your data. Targets your 3 weakest note transitions!',
    'AI-generated workout. Difficulty: matched to your skill ceiling. Let\'s GO!',
    'Personalized exercise based on 47 performance data points. Made for you!',
    'This drill attacks your weak spots. The algorithm doesn\'t miss!',
    'Built from your stats: timing gaps, pitch accuracy, tempo range. Tailored training!',
  ],
  achievement_unlock: [
    'Achievement unlocked! Another badge in the trophy case. Let\'s GO!',
    'Boom! You hit the criteria and earned that one. Stats updated!',
    'New badge! Performance threshold: exceeded. That\'s a certified W!',
    'Trophy earned! Add it to the collection. Keep stacking achievements!',
    'Badge: EARNED. The leaderboard notices players who collect these!',
  ],
  streak_milestone: [
    'Streak milestone! Consecutive days: climbing. You\'re in the top 8% of all players!',
    'Day after day! Consistency score: elite. This streak is record-breaking territory!',
    'Your streak just hit a new high. That\'s more reliable than a metronome!',
    'Impressive! Zero days missed. That kind of discipline separates the best from the rest!',
    'Streak stats: LOCKED IN. You show up every single day. No one can take that from you!',
  ],
  demoOffer: [
    'Study the playback. Watch the timing intervals— that\'s your game plan!',
    'Demo mode: ON. Focus on the rhythm pattern. Absorb, then execute!',
    'Let me show you the optimal path through this drill. Watch the beat markers!',
    'Reviewing the tape first. Smart players study before they perform!',
    'Visual demo incoming. Lock in on the timing— that\'s where the points are!',
  ],
  demoComplete: [
    'Demo done. Your turn. Apply what you saw. Target: match that timing!',
    'Playback complete. Now execute! The data says you can hit 80%+ on this!',
    'Pattern locked in? Good. Now replicate it. Tracking is live!',
    'Reference set. Go time! Show me you absorbed those timing patterns!',
    'Film study\'s over. Now it\'s game time— perform! Let\'s GO!',
  ],
  ghostNotesFarewell: [
    'Guide notes: OFF. You don\'t need them anymore. That\'s incredible performance!',
    'Training wheels removed. Your accuracy is self-sufficient now. Well done!',
    'No more assists. You\'ve graduated to full solo performance. That\'s elite!',
    'Ghost notes disabled. Muscle memory: locked in. Great work earning this!',
    'Helpers gone. Stats prove you\'re ready to fly solo. Let\'s GO!',
  ],
};

const SHIBU: CatMessages = {
  exercise_start: [
    'Breathe... the river does not rush to the sea.',
    'Place your hands like stones at the water\'s edge. Begin when the stillness speaks.',
    'The bamboo waits for wind. You wait for the first note.',
    'A single breath. Then the mountain answers with music.',
    'Still your mind... the keys are patient as old stone.',
  ],
  exercise_mid_great: [
    'Like water finding its path. You did not force the music... you became it.',
    'The reed bends perfectly. Your notes carry that same grace.',
    'Smooth as a stone worn by the river. Nothing wasted.',
    'Wind through bamboo. That is what your playing sounds like now.',
    'Even the mountain listened just then.',
  ],
  exercise_mid_miss: [
    'A leaf falls from the branch. The tree remains.',
    'The river meets a stone... and flows around it. Continue.',
    'Breathe... one missed note is morning frost. It melts.',
    'Even still water has ripples. Let this one pass.',
    'The wind shifted. Find your center again.',
  ],
  exercise_complete_pass: [
    'Like rain arriving exactly when the garden needed it.',
    'The mountain stands. Your music echoed well against it.',
    'You found the river\'s pace. That is a rare thing.',
    'Bamboo grows in silence. So did your skill just now.',
    'A stone placed well in the garden. Nothing more was needed.',
  ],
  exercise_complete_fail: [
    'The seed does not bloom on the first rain. Return to the soil.',
    'A mountain is climbed many times before its peak is known.',
    'The river tried a new path... it will find its way.',
    'Even bamboo bends before it stands tall. Try once more.',
    'Do not carry this weight. Set it down like a stone by the water.',
  ],
  level_up: [
    'Mist rises from the valley. You have risen with it.',
    'Another ring in the old tree. Quiet, steady growth.',
    'The mountain path turns... and the view is wider now.',
    'Like a river reaching a broader valley. You have expanded.',
    'Bamboo does not announce its growth. Neither must you.',
  ],
  daily_login: [
    'The stones are where you left them. Welcome back.',
    'Morning light on still water. A good time to play.',
    'You return... like the tide. The keys remember you.',
    'The garden waited. Now it stirs.',
    'Another dawn. The bamboo is already practicing.',
  ],
  idle: [
    'Silence between notes... this too is music.',
    'The pond is still. When you are ready, cast your stone.',
    'Rest is not absence. It is the space between breaths.',
    'Even the wind pauses... then begins again.',
    'The mountain does not hurry. Neither should you.',
  ],
  ai_exercise_intro: [
    'A path was laid for you. Walk it as the river walks... without forcing.',
    'This practice was chosen like a stone chosen for the garden. It belongs here.',
    'The wind brought this exercise to your door. Accept it gently.',
    'Crafted for where you are now... not where you wish to be.',
    'Breathe... then step onto this new path with soft feet.',
  ],
  achievement_unlock: [
    'A small stone added to the cairn. The pile grows.',
    'Recognition falls like a single petal. Receive it quietly.',
    'The mountain does not seek praise... but it is beautiful regardless.',
    'You earned this the way rivers earn the sea. Slowly and surely.',
    'Like a bell struck once in an empty temple. It resonates.',
  ],
  streak_milestone: [
    'The river has not stopped. Day after day, it flows.',
    'Each day a single step. Look how far the path stretches behind you.',
    'Bamboo grows one segment at a time. Your streak is the same.',
    'The tide returns without fail. So do you.',
    'Consistency is the deepest root of the oldest tree.',
  ],
  demoOffer: [
    'Watch as the water shows you its path. Simply observe.',
    'I will play it once, like wind passing through the reeds. Listen.',
    'Breathe... and let the demonstration flow over you like a stream.',
    'Close your eyes first. Then open them and watch.',
    'The bamboo will show you how it bends. Just be present.',
  ],
  demoComplete: [
    'Now the melody lives in your hands. Let it surface like a spring.',
    'You have seen the river\'s path. Now walk along the bank yourself.',
    'The wind showed you its direction. Follow it with your own breath.',
    'Begin when the stillness tells you it is time.',
    'Your turn. Play as the mountain listens.',
  ],
  ghostNotesFarewell: [
    'The lanterns on the path go dark. You no longer need their light.',
    'Like morning mist lifting from the valley... the guides dissolve.',
    'The river removed its stepping stones. You can swim now.',
    'No more markers on the trail. Your feet know the way.',
    'The bamboo scaffold falls away. The vine stands alone.',
  ],
};

const BELLA: CatMessages = {
  exercise_start: [
    'Shall we begin, darling? One does not simply rush into a performance.',
    'Posture, please. A refined recital begins before the first note is struck.',
    'Very well then. Let us craft something rather exquisite together.',
    'The salon awaits your contribution, darling. Do make it splendid.',
    'One must approach the keys with the poise of old heritage. Begin.',
  ],
  exercise_mid_great: [
    'Quite exquisite, darling. One does not simply play music... one inhabits it.',
    'Rather splendid, indeed. That note had the elegance of fine porcelain.',
    'Darling, that was positively distinguished. Do carry on just like that.',
    'Magnificent phrasing. One could almost mistake you for conservatory-trained.',
    'Splendid. Quite splendid. You\'re beginning to play with real refinement.',
  ],
  exercise_mid_miss: [
    'A minor indiscretion, darling. We shall pretend that never happened.',
    'Even the finest pearls have a tiny blemish. Do compose yourself and carry on.',
    'Rather unfortunate, but one does not dwell. The next note awaits your grace.',
    'Quite forgivable, darling. A lady never mentions such things twice.',
    'One small misstep does not ruin the entire gala. Onwards, indeed.',
  ],
  exercise_complete_pass: [
    'A performance quite worthy of the finest salon, darling. Splendid work.',
    'Exquisite from start to finish. One is rather genuinely impressed, indeed.',
    'Darling, that was positively regal. You should be quite proud of yourself.',
    'Rather magnificent. I dare say the Steinway itself is blushing.',
    'Splendid, darling. That had the polish of proper heritage.',
  ],
  exercise_complete_fail: [
    'Rome was not built in a day, darling, and neither is true refinement.',
    'Even Debussy had his difficult drafts. One simply tries once more.',
    'Quite alright, darling. Elegance requires patience above all else.',
    'Do not fret. Grace under pressure is rather the mark of true class.',
    'A temporary setback for someone of your considerable potential, indeed.',
  ],
  level_up: [
    'How distinguished, darling. A new level quite befitting your talent.',
    'Ascending the ranks with poise and grace. Rather expected of you, indeed.',
    'Splendid. You are becoming quite the accomplished pianist, darling.',
    'A promotion most deserved. One step closer to true musical refinement.',
    'Your growth is as elegant as a Debussy prelude. Quite lovely.',
  ],
  daily_login: [
    'Ah, you\'ve returned, darling. The piano was getting rather lonely without you.',
    'Welcome back. I trust you\'re well-rested and quite ready to play.',
    'How lovely to see you. Shall we make something rather beautiful today?',
    'Good day, darling. I\'ve kept everything quite pristine in your absence.',
    'The keys gleam in anticipation, indeed. Do take your seat.',
  ],
  idle: [
    'One does not simply leave a Steinway unattended, darling.',
    'The silence is becoming rather undignified. Shall we resume?',
    'Are we on a break? One was not informed, quite frankly.',
    'Darling, the keys grow restless. As, indeed, do I.',
    'A proper musician does not leave the audience waiting. Rather rude, that.',
  ],
  ai_exercise_intro: [
    'A bespoke exercise, darling. Tailored quite specifically to your refined sensibilities.',
    'Custom-crafted, rather like a couture gown for your fingers. Splendid.',
    'The algorithm has excellent taste, indeed. This one suits you, darling.',
    'Only the finest, most curated selections for someone of your caliber.',
    'A personalized piece, darling. One does not simply give you anything off the rack.',
  ],
  achievement_unlock: [
    'A trophy, darling. How quite fitting for someone of your caliber.',
    'You\'ve earned this distinction rather handsomely. Wear it with pride, indeed.',
    'Splendid. An achievement as polished as a strand of fine pearls.',
    'Another jewel in your crown, darling. How perfectly appropriate.',
    'Recognition quite befitting your elegant playing. Well deserved, indeed.',
  ],
  streak_milestone: [
    'Your consistency is as reliable as fine crystal, darling. Quite impressive.',
    'Day after day of rather refined practice. One is genuinely moved.',
    'A streak this elegant could grace any concert hall in Vienna, indeed.',
    'Dedication and discipline, darling. The hallmarks of true class.',
    'Splendid commitment. Your devotion to excellence rather never wavers.',
  ],
  demoOffer: [
    'Allow me to demonstrate, darling. One must observe proper technique firsthand.',
    'I shall show you the rather refined way to approach this piece. Watch closely.',
    'Observe, darling. Elegance is quite entirely in the details, indeed.',
    'Let me play it through first. Do take note of the phrasing, won\'t you.',
    'A demonstration of impeccable taste, darling. You are rather welcome.',
  ],
  demoComplete: [
    'Now it is your turn, darling. Do try to match that level of elegance.',
    'You\'ve seen how it is done quite properly. Show me your very best, indeed.',
    'The demonstration is complete, darling. I expect nothing less than grace.',
    'Your turn. Remember: poise, posture, and rather impeccable execution.',
    'Go ahead, darling. Make it as refined and splendid as you are.',
  ],
  ghostNotesFarewell: [
    'The guide notes have been dismissed, darling. You no longer require their service.',
    'Playing without assistance, quite independently. Rather wonderful, indeed.',
    'The training notes curtsy and exit the stage. Your own talent shines splendidly.',
    'No more hand-holding, darling. You play with the confidence of proper royalty.',
    'You\'ve graduated beyond the guides, indeed. Quite extraordinary, darling.',
  ],
};

const SABLE: CatMessages = {
  exercise_start: [
    'Interesting... let\'s see what you\'ve got.',
    'Hmm. The keys are waiting. So am I.',
    'Most students hesitate before they start. Don\'t be most students.',
    'I notice you\'re ready. Good. Begin.',
    'Curious... something about tonight feels different. Play.',
  ],
  exercise_mid_great: [
    'Hmm. Interesting. Most students take three tries. You did it in one.',
    'Not bad. Not bad at all.',
    'I notice your fingers knew exactly where to go. Curious.',
    'Interesting... that was cleaner than I expected.',
    'Most wouldn\'t catch that rhythm. You did.',
  ],
  exercise_mid_miss: [
    'Hmm. Noted. Move on.',
    'Interesting... that note told me more about you than the correct ones did.',
    'A slip. Not the first. Won\'t be the last. Continue.',
    'I notice you flinched. Don\'t. Just keep playing.',
    'Most would stop there. You\'re not most.',
  ],
  exercise_complete_pass: [
    'Hmm. Well played. I almost smiled.',
    'Not bad. The evidence suggests you actually practiced.',
    'Interesting... you\'re better than you were yesterday. I notice these things.',
    'Most wouldn\'t have pulled that off. But you\'re not most.',
    'I\'ve been watching. That was solid.',
  ],
  exercise_complete_fail: [
    'Hmm. Not your best. But I\'ve seen worse.',
    'Interesting... the mistakes reveal where the real work begins.',
    'Most give up after a round like that. Something tells me you won\'t.',
    'I notice the pattern. Fix the third passage and the rest follows.',
    'Not quite. But the shadows between attempts are where growth hides.',
  ],
  level_up: [
    'Hmm. You leveled up. I\'m not surprised.',
    'Interesting... I had a feeling you were close. I was right.',
    'Most don\'t get here this quickly. I noticed your pace weeks ago.',
    'A new level. The view from here is different. Pay attention.',
    'Curious. You\'re growing faster than you realize.',
  ],
  daily_login: [
    'You\'re back. I noticed.',
    'Hmm. Right on time. Interesting.',
    'Most don\'t return this consistently. You\'re not most.',
    'I was watching the door. Not that I\'d admit it.',
    'Curious... something brought you back. Let\'s find out what.',
  ],
  idle: [
    'Hmm. The silence is saying more than you think.',
    'I notice you\'ve stopped. Interesting.',
    'Most lose focus around this point. Prove me wrong.',
    'The keys are getting cold. Just an observation.',
    'Curious... are you thinking, or hesitating? There\'s a difference.',
  ],
  ai_exercise_intro: [
    'Interesting... this one was picked specifically for you. I wonder why.',
    'Hmm. A custom exercise. The algorithm noticed something I noticed too.',
    'Most get standard drills. You got something tailored. Curious.',
    'I notice this targets your weak spot. Smart.',
    'A personalized challenge. Not bad. Let\'s see how you handle it.',
  ],
  achievement_unlock: [
    'Hmm. An achievement. You earned it. I\'m not easily impressed, but noted.',
    'Interesting... most miss that one entirely. You didn\'t.',
    'I notice you\'ve been collecting these quietly. Respect.',
    'An achievement unlocked. I had my eye on this one for you.',
    'Curious. Most wouldn\'t have noticed, but I always do.',
  ],
  streak_milestone: [
    'Hmm. That streak. Interesting. Most break by day five.',
    'I notice you haven\'t missed a day. That tells me everything.',
    'Not bad. Consistency is the hardest skill. You make it look easy.',
    'Curious... your streak is longer than most people\'s entire practice history.',
    'Most talk about dedication. You just show up. I respect that.',
  ],
  demoOffer: [
    'Watch closely. I\'ll show you once. That should be enough.',
    'Hmm. Let me demonstrate. Pay attention to the details.',
    'I notice you need a reference. Fair enough. Observe.',
    'Most wouldn\'t catch the subtleties. Try to be the exception.',
    'Interesting... I\'ll play it through. Watch what my fingers do, not just the notes.',
  ],
  demoComplete: [
    'Now you. I\'ll be watching.',
    'Hmm. Your turn. Show me what you noticed.',
    'The demo\'s done. Let\'s see if you caught the important parts.',
    'Most miss the nuance on first watch. Prove me wrong.',
    'Interesting... now show me your version. I\'m curious.',
  ],
  ghostNotesFarewell: [
    'Hmm. No more guide notes. I noticed you stopped needing them a while ago.',
    'Interesting... playing solo now. Most aren\'t ready this soon.',
    'The training wheels are gone. I\'m not surprised. You were ready.',
    'I notice you didn\'t even flinch when they disappeared. Good.',
    'Curious. Most cling to the guides. You just let them go.',
  ],
};

const CODA: CatMessages = {
  exercise_start: [
    'Initializing exercise module. All systems nominal. Begin when ready.',
    'Pre-flight check: tempo loaded, key signature parsed. Execution may commence.',
    'Data suggests optimal readiness. Starting playback sequence now.',
    'Input detected: user is prepared. Running exercise protocol.',
    'Calibration complete. Timing window: active. Proceed.',
  ],
  exercise_mid_great: [
    'Execution: flawless. Timing deviation: minimal. Conclusion: you\'re getting seriously good.',
    'Analysis complete. That note registered within 5 milliseconds of target. Impressive.',
    'Data point logged: accuracy trending upward. Maintain current trajectory.',
    'Technically speaking, that was optimal. Zero corrections needed.',
    'Pattern match: successful. Your muscle memory subroutine is compiling nicely.',
  ],
  exercise_mid_miss: [
    'Error logged. Timing offset: significant. Recommended action: recalibrate and continue.',
    'Deviation detected. Not critical. Adjusting expectations for next note.',
    'Technically speaking, that was suboptimal. But the recovery window is open.',
    'Bug report filed. Root cause: likely a timing sync issue. Carry on.',
    'One incorrect input does not corrupt the full dataset. Proceed.',
  ],
  exercise_complete_pass: [
    'Analysis complete. Performance metrics: above threshold. Status: passed.',
    'Final score compiled. Data suggests genuine improvement since last session.',
    'Execution summary: accuracy high, timing consistent. Verdict: well done.',
    'Technically speaking, that was a clean run. Logging as successful build.',
    'All parameters within target range. Performance: validated.',
  ],
  exercise_complete_fail: [
    'Build failed. But the error log is instructive. Review and recompile.',
    'Analysis: below threshold. However, data shows progress in subsections.',
    'Technically speaking, failure is just unfinished debugging. Try again.',
    'Performance did not pass validation. Root cause identified: practice needed.',
    'Incomplete execution. The algorithm recommends another iteration.',
  ],
  level_up: [
    'Level increment detected. Skill index: updated. New tier: unlocked.',
    'Version upgrade: complete. You\'re running on improved firmware now.',
    'Data confirms: level threshold exceeded. Promoting to next rank.',
    'Technically speaking, your growth rate exceeds projected benchmarks.',
    'System log: user has leveled up. All downstream modules notified.',
  ],
  daily_login: [
    'Session initiated. Welcome back. Your practice data awaits.',
    'Login detected. Time since last session: within optimal range.',
    'Technically speaking, punctuality correlates with faster improvement. Good timing.',
    'User authenticated. Loading your progress profile now.',
    'Daily check-in logged. Streak integrity: maintained.',
  ],
  idle: [
    'Idle timeout approaching. Input required to maintain session.',
    'No activity detected. System entering low-power observation mode.',
    'Technically speaking, rest periods are valid. But this one is getting long.',
    'Awaiting user input. The exercise module is still loaded and ready.',
    'Idle state detected. Recommendation: resume before context is lost.',
  ],
  ai_exercise_intro: [
    'Custom exercise generated. Parameters tuned to your weakness profile.',
    'Algorithm output: one tailored exercise targeting your lowest-scoring patterns.',
    'Technically speaking, this was optimized for maximum skill transfer.',
    'Data-driven selection: this exercise addresses your most frequent error types.',
    'Personalized training module loaded. Calibrated to your current performance data.',
  ],
  achievement_unlock: [
    'Achievement unlocked. Condition met: verified. Adding to your record.',
    'Badge earned. Technically speaking, fewer than 20 percent of users reach this one.',
    'New achievement logged. Cross-referencing with skill index: correlation confirmed.',
    'Data point: you\'ve unlocked something notable. Flagging for recognition.',
    'Achievement registered. Your completion percentage just ticked upward.',
  ],
  streak_milestone: [
    'Streak counter: impressive. Uptime percentage: exceptional.',
    'Consecutive days logged. Technically speaking, consistency is the strongest predictor of mastery.',
    'Data analysis: your streak places you in the top tier of active users.',
    'No gaps detected in practice log. That kind of reliability is rare.',
    'Streak milestone reached. The data is clear: you don\'t skip days.',
  ],
  demoOffer: [
    'Loading demonstration mode. Observe the target execution pattern.',
    'Technically speaking, watching a reference run reduces error rate by 40 percent. Observe.',
    'Demo sequence: ready. Pay attention to timing markers and note placement.',
    'Initiating playback example. Recommended: focus on the transition points.',
    'Reference performance loading. Study the output carefully.',
  ],
  demoComplete: [
    'Demo complete. Your turn. Apply the observed pattern.',
    'Reference data delivered. Technically speaking, your next attempt should improve.',
    'Demonstration: finished. Now replicate with your own input.',
    'The example has been logged. Execute your version now.',
    'Observation phase: complete. Switching to active input mode.',
  ],
  ghostNotesFarewell: [
    'Guide overlay: disabled. You no longer require the reference layer.',
    'Training scaffolding removed. Technically speaking, you\'ve internalized the patterns.',
    'Assistance module: deactivated. Your autonomous performance is sufficient.',
    'No more hints in the pipeline. Data confirms you can operate independently.',
    'Guide notes: deprecated. Your own runtime is stable enough.',
  ],
};

const ALL_DIALOGUES: Record<string, CatMessages> = {
  'mini-meowww': MINI_MEOWWW,
  'jazzy': JAZZY,
  'chonky-monke': CHONKY_MONKE,
  'luna': LUNA,
  'biscuit': BISCUIT,
  'ballymakawww': BALLYMAKAWWW,
  'aria': ARIA,
  'tempo': TEMPO,
  'shibu': SHIBU,
  'bella': BELLA,
  'sable': SABLE,
  'coda': CODA,
};

const CONDITION_OVERRIDES: Record<string, Partial<Record<DialogueTrigger, Partial<Record<DialogueCondition, string[]>>>>> = {
  'mini-meowww': {
    exercise_complete_pass: {
      score_high: [
        'OH MY GOSH!! PERFECT SCORE!! I\'m gonna EXPLODE!!',
        'Three stars!! THREE STARS!! This is the best!!',
        'You are LITERALLY the best pianist EVER!!',
      ],
      first_try: [
        'First try?! FIRST TRY?! You\'re a genius!!',
        'Nailed it on the first go!! Incredible!!',
      ],
    },
  },
  'tempo': {
    exercise_complete_pass: {
      score_high: [
        'Score: 95%+. Exceptional. Top percentile performance.',
        'Accuracy: maximum. No deviations detected.',
        'Perfect execution. Logging as reference performance.',
      ],
    },
  },
};

export function getCatDialogue(
  catId: string,
  trigger: DialogueTrigger,
  condition?: DialogueCondition
): string[] {
  const catMessages = ALL_DIALOGUES[catId] ?? ALL_DIALOGUES['mini-meowww'];

  if (condition) {
    const overrides = CONDITION_OVERRIDES[catId]?.[trigger]?.[condition];
    if (overrides && overrides.length > 0) {
      return overrides;
    }
  }

  return catMessages[trigger] ?? catMessages.exercise_start;
}

export function getRandomCatMessage(
  catId: string,
  trigger: DialogueTrigger,
  condition?: DialogueCondition
): string {
  const messages = getCatDialogue(catId, trigger, condition);
  return messages[Math.floor(Math.random() * messages.length)];
}
