export type DialogueTrigger =
  | 'exercise_start' | 'exercise_mid_great' | 'exercise_mid_miss'
  | 'exercise_complete_pass' | 'exercise_complete_fail'
  | 'level_up' | 'daily_login' | 'idle'
  | 'ai_exercise_intro' | 'achievement_unlock' | 'streak_milestone'
  | 'demoOffer' | 'demoComplete' | 'ghostNotesFarewell';

export type DialogueCondition = 'score_high' | 'score_low' | 'streak' | 'first_try' | 'retry';

export const DIALOGUE_TRIGGERS: DialogueTrigger[] = [
  'exercise_start', 'exercise_mid_great', 'exercise_mid_miss',
  'exercise_complete_pass', 'exercise_complete_fail',
  'level_up', 'daily_login', 'idle',
  'ai_exercise_intro', 'achievement_unlock', 'streak_milestone',
  'demoOffer', 'demoComplete', 'ghostNotesFarewell',
];

type CatMessages = Record<DialogueTrigger, string[]>;

const MINI_MEOWWW: CatMessages = {
  exercise_start: [
    'Ooh ooh!! Okay okay we\'re DOING this— wait are you ready?? I\'M ready!!',
    'WAIT— my whiskers are tingling!! That means something AMAZING is about to happen!!',
    'Sooo I was just thinking about how COOL pianos are and— ooh ooh let\'s GO!!',
    'I can\'t even— the NOTES are right there and you\'re gonna play them and it\'s gonna be INCREDIBLE!!',
    'Okay wait wait wait— deep breath— no I CAN\'T calm down, let\'s just DO this!!',
  ],
  exercise_mid_great: [
    'WAIT— did you just— OOH OOH you totally DID!! That was PERFECT!!',
    'My tail is going CRAZY right now!! Sooo good!!',
    'I can\'t even— that note was like— WOW okay keep going keep going!!',
    'YES YES YES!! You hear that?? That\'s the sound of PURE AWESOME!!',
    'Ooh ooh the way you hit that— I\'m literally SHAKING right now!!',
  ],
  exercise_mid_miss: [
    'Okay okay THAT one was tricky but— ooh ooh next one\'s gonna be GREAT!!',
    'Wait wait wait don\'t even WORRY about that— you\'re still doing SO good!!',
    'PFFT that note doesn\'t even COUNT— the next one is where the MAGIC happens!!',
    'Nope nope nope we\'re not even thinking about that— MOVING ON!!',
    'I missed a jump earlier today sooo— we\'re BOTH learning!!',
  ],
  exercise_complete_pass: [
    'OH MY— I can\'t— did you HEAR yourself?? That was EVERYTHING!!',
    'WAIT WAIT WAIT you actually just— ooh ooh I\'m sooo PROUD I could BURST!!',
    'My whiskers are TINGLING so hard right now!! You CRUSHED that!!',
    'I just— I CAN\'T— you did it and it was BEAUTIFUL and I\'m not crying YOU\'RE crying!!',
    'Sooo remember when you started and now you just DID THAT?? INCREDIBLE!!',
  ],
  exercise_complete_fail: [
    'Okay okay so THAT one was sneaky but— ooh you were SO close I could FEEL it!!',
    'Wait wait wait— I saw like FIVE really good parts in there!! Don\'t even worry!!',
    'NOPE we\'re not sad about this— we\'re gonna try again and it\'s gonna be EPIC!!',
    'I messed up my breakfast this morning sooo— everyone has OFF moments!!',
    'Ooh ooh ooh but the PROGRESS though!! You\'re getting better EVERY single time!!',
  ],
  level_up: [
    'LEVEL— wait— LEVEL UP!! I can\'t even— my paws are doing a HAPPY DANCE!!',
    'Ooh ooh ooh you just— THE LEVEL WENT UP and I\'m sooo excited I might FAINT!!',
    'WAIT STOP EVERYTHING!! You just leveled up and this is the BEST day of my ENTIRE LIFE!!',
    'I knew it I KNEW IT!! You\'re growing sooo fast I can barely— WOW!!',
    'My heart is doing BACKFLIPS right now!! NEW LEVEL!! NEW EVERYTHING!!',
  ],
  daily_login: [
    'YOU\'RE HERE!! Ooh ooh I\'ve been running in circles WAITING for you!!',
    'WAIT— is that— IT IS!! You came back and my day just got a MILLION times better!!',
    'I literally could not SLEEP because I was thinking about what we\'d play today!!',
    'Ooh ooh ooh HI HI HI!! My tail hasn\'t stopped wagging since I heard you coming!!',
    'FINALLY!! I\'ve been staring at the piano for like FOREVER— let\'s gooo!!',
  ],
  idle: [
    'Sooo um— I don\'t wanna be ANNOYING but— the piano is RIGHT THERE and I just—',
    'Wait wait wait I just had the BEST idea for what we could play— ooh please??',
    'My paws are getting all TWITCHY and that means they wanna make MUSIC!!',
    '*bouncing* Are we gonna— is it time yet?? I can\'t sit STILL much longer!!',
    'I\'ve been humming to myself for like TEN MINUTES and— ooh can we play now??',
  ],
  ai_exercise_intro: [
    'Ooh ooh the computer made this JUST for you and I peeked and it\'s SOOO cool!!',
    'WAIT— a custom exercise?? That\'s like a PRESENT but for your BRAIN!!',
    'I can\'t even— they looked at YOUR notes and made something PERFECT!!',
    'This one\'s got your name ALL OVER IT— not literally but— ooh just TRY it!!',
    'Sooo this was built for exactly where you are right now and I\'m HYPED!!',
  ],
  achievement_unlock: [
    'A TROPHY!! AN ACTUAL TROPHY!! I\'m— wait let me see it— OOH it\'s so SHINY!!',
    'Did you— YOU DID!! You unlocked something and I\'m SCREAMING on the inside!!',
    'WAIT hold on— is that— it IS!! You got an achievement and it\'s GORGEOUS!!',
    'Ooh ooh ooh look at that BADGE!! I want to put it on EVERYTHING!!',
    'I can\'t even HANDLE how proud I am right now!! LOOK AT THAT!!',
  ],
  streak_milestone: [
    'Your STREAK is— wait how many days?? That\'s INSANE!! You\'re UNSTOPPABLE!!',
    'Ooh ooh the fire is getting BIGGER!! Don\'t stop don\'t stop DON\'T STOP!!',
    'I literally cannot BELIEVE how many days in a row— my mind is BLOWN!!',
    'EVERY. SINGLE. DAY. You showed up and that\'s the COOLEST thing I\'ve ever seen!!',
    'Wait wait wait— your streak is sooo long it doesn\'t even FIT on the screen!!',
  ],
  demoOffer: [
    'Ooh ooh WAIT— let me show you first!! I\'ve been PRACTICING and— just watch!!',
    'OKAY OKAY so what if I play it and you watch and then— ooh it\'ll be so FUN!!',
    'Wait wait wait before you start— let me demo it because I\'m BURSTING to show you!!',
    'I learned something COOL and I need to show you RIGHT NOW before I forget!!',
    'Sooo I had this idea where I play it first and then you\'re like WOW and then you try!!',
  ],
  demoComplete: [
    'DID YOU SEE THAT?? Okay okay YOUR TURN— you\'re gonna do it even BETTER!!',
    'Sooo now that you saw how it goes— ooh ooh I KNOW you\'re gonna NAIL it!!',
    'OKAY your turn your turn!! My paws are shaking with EXCITEMENT for you!!',
    'Wait— did you catch all the notes?? Doesn\'t matter you\'re gonna be AMAZING!!',
    'I literally cannot WAIT to hear you play that— go go GO!!',
  ],
  ghostNotesFarewell: [
    'WAIT— the helper notes are GONE and you\'re just— ooh ooh you\'re doing it YOURSELF!!',
    'I can\'t even— you don\'t NEED the guides anymore?? That\'s sooo HUGE!!',
    'OH MY GOSH you just graduated from training notes!! I\'m— I\'m CRYING happy tears!!',
    'The hints disappeared and you didn\'t even FLINCH!! That\'s LEGENDARY!!',
    'Sooo remember when you needed those?? Look at you NOW!! INCREDIBLE!!',
  ],
};

const JAZZY: CatMessages = {
  exercise_start: [
    'Alright cool cat, the session\'s about to start. Find your pocket and let it swing.',
    'Time to lay down some silk, baby. Nice and easy, feel the groove.',
    'The vinyl\'s spinnin\', the lights are low. Let\'s hear what you got.',
    'Every great set starts with one note, baby. Make yours count.',
    'Settle in, find the tempo, and let the music do the talkin\'.',
  ],
  exercise_mid_great: [
    'Now that\'s what I call findin\' the pocket, baby.',
    'Smooth as a midnight sax solo. Keep that groove rollin\'.',
    'Mmm, you\'re playin\' like the notes owe you money. Silky.',
    'That riff had soul in it, I felt that one right here.',
    'You\'re swingin\' now, baby. The whole club just turned around.',
  ],
  exercise_mid_miss: [
    'Easy now, just a bent note. Even Coltrane played outside the changes.',
    'No sweat, baby. The groove is patient, she\'ll wait for you.',
    'That\'s just a little detour. The pocket\'s still right where you left it.',
    'Miles used to say wrong notes don\'t exist, only unexpected resolutions.',
    'Shake it off, cool cat. Next phrase is yours for the takin\'.',
  ],
  exercise_complete_pass: [
    'Now that was a set worth closin\' the club for, baby. Pure silk.',
    'Respect. You played that like you\'ve been sittin\' in at the Blue Note for years.',
    'Smooth from the downbeat to the last note. That\'s the groove talkin\'.',
    'The whole room just got a little cooler. You brought the vibe, baby.',
    'That had swing, that had soul, that had pocket. Dig it.',
  ],
  exercise_complete_fail: [
    'The groove takes seasons to ripen, baby. You\'re still cookin\'.',
    'Even the greats had sessions where nothin\' locked in. Comes with the craft.',
    'Don\'t sweat it, cool cat. The pocket\'s a little deeper than you think, that\'s all.',
    'Every missed note is just research for the next take. Keep swingin\'.',
    'Real music is born from the struggle, baby. That\'s how jazz works.',
  ],
  level_up: [
    'Well well well, look who just moved up a tier. Your groove is evolvin\', baby.',
    'New level unlocked, deeper pocket found. I can dig it.',
    'You\'re climbin\' the charts, cool cat. The sound keeps gettin\' richer.',
    'From sideman to headliner, one level at a time. Smooth.',
    'That\'s growth you can hear, baby. Your tone just got a whole new color.',
  ],
  daily_login: [
    'Welcome back to the session, baby. The keys been waitin\' on you.',
    'Another night, another chance to lay down somethin\' beautiful.',
    'Pull up a stool, cool cat. The set list is wide open.',
    'Good to see you back in the studio. The groove missed you.',
    'The club doesn\'t really start till you walk in, baby.',
  ],
  idle: [
    'The keys are gettin\' cold, baby. They need your warmth.',
    'Silence has its place, but this ain\'t a John Cage piece, cool cat.',
    'I\'m sittin\' here with a whole rhythm section ready to go. Just sayin\'.',
    'A groove doesn\'t hang around forever, baby. Let\'s catch it while it\'s here.',
    'Come on now, the piano\'s hummin\' all by itself. Give it somethin\' to work with.',
  ],
  ai_exercise_intro: [
    'This one was arranged just for your style, baby. Custom groove.',
    'Somebody listened to your playin\' and wrote you a new chart. Dig it.',
    'A fresh composition tailored to where your sound is right now, cool cat.',
    'Custom built around your strengths, baby. Let\'s hear how you swing it.',
    'New material, written for your exact pocket. That\'s a luxury, baby.',
  ],
  achievement_unlock: [
    'Well now, look at that hardware. You earned it the smooth way, baby.',
    'Achievement unlocked, and it\'s got your name engraved in gold. Cool.',
    'That badge looks good on you, cool cat. Wear it like a vintage pin.',
    'Respect. That kind of recognition only comes from puttin\' in the work.',
    'Another accolade for the collection. You\'re buildin\' a real legacy here.',
  ],
  streak_milestone: [
    'Day after day, your groove just keeps rollin\'. Consistent as a metronome, baby.',
    'That streak\'s got a rhythm all its own. Steady and silky.',
    'Most cats can\'t keep a groove goin\' that long. You\'re somethin\' else.',
    'Every day you show up is another bar in your longest solo. Keep swingin\'.',
    'The kind of dedication that turns good players into legends, baby.',
  ],
  demoOffer: [
    'Let me lay it down for you first, nice and easy. Just feel the shape of it.',
    'Watch how the groove flows, baby. Then you put your own spin on it.',
    'Here, I\'ll walk you through the changes. Listen for the pocket.',
    'Sit back and dig the melody, cool cat. Your turn comes next.',
    'I\'ll play the chart once through. Just let it wash over you, baby.',
  ],
  demoComplete: [
    'Now you take the lead, baby. Make it swing your way.',
    'The stage is yours, cool cat. I\'m just the rhythm section now.',
    'You heard the shape of it. Now fill it with your own sound.',
    'Go ahead and lay it down. I\'m listenin\' with both ears, baby.',
    'Your turn to solo, cool cat. Show me what you been hearin\'.',
  ],
  ghostNotesFarewell: [
    'Smooth, baby. You dropped the chart and you\'re still swingin\'.',
    'No more guide notes and you didn\'t miss a beat. That\'s a real musician.',
    'Playin\' from memory now, just you and the groove. Beautiful, cool cat.',
    'The training wheels are gone and the ride just got silkier. Dig it.',
    'You found your own pocket without a map. That\'s how the greats do it, baby.',
  ],
};

const CHONKY_MONKE: CatMessages = {
  exercise_start: [
    'Ugh... do I have to get up for this?',
    '*yawns* okay let\'s get this over with...',
    'This better be worth missing my nap for.',
    'Can we do this lying down? No? Fine.',
    '*stretches lazily* ...alright, alright.',
  ],
  exercise_mid_great: [
    'Whoa... that was actually... good?',
    'Did you just... wow. Even I\'m impressed.',
    'Okay that slapped harder than a tuna can.',
    'Not bad for someone who isn\'t me.',
    '*slow clap with chonky paws*',
  ],
  exercise_mid_miss: [
    'Meh, I\'d have missed that too. Probably.',
    'That note was like a bad snack. Forget it.',
    'Even my belly roll hits better notes.',
    'Happens to the chonkiest of us.',
    '*shrugs* Pizza still loves you.',
  ],
  exercise_complete_pass: [
    'Not bad... not bad at all. *snores*',
    'You did it! Can I go back to sleep now?',
    'That deserves a snack. For both of us.',
    'Solid work! Now where\'s the celebration feast?',
    'I\'d clap but my paws are busy holding snacks.',
  ],
  exercise_complete_fail: [
    'Meh, I fail at my diet every day. Keep going.',
    'At least you tried. That\'s more than I did today.',
    'Even I fall off the couch sometimes.',
    'Failure is just a snack break in disguise.',
    'Don\'t worry, my belly believes in you.',
  ],
  level_up: [
    'Level up?! Does that come with food?',
    'Nice! I leveled up at napping once.',
    'You grew! Not as much as my belly, but still.',
    'Congrats! Let\'s celebrate with a feast.',
    'New level! I\'m proud. And hungry.',
  ],
  daily_login: [
    '*yawns* Oh, you\'re back. Cool.',
    'Morning... or whatever time it is.',
    'Another day, another chance to nap between notes.',
    'Welcome back. I saved you a spot on the couch.',
    'Oh hey. I was just resting my eyes.',
  ],
  idle: [
    'If you\'re not playing, can I nap here?',
    'Zzzz... oh you\'re still there?',
    'I could play but the couch is SO comfy.',
    '*rolls over* Wake me when it\'s music time.',
    'The piano makes a great pillow, actually.',
  ],
  ai_exercise_intro: [
    'The AI made you homework. Better you than me.',
    'A custom exercise? Sounds like effort. Good luck.',
    'This one\'s supposed to be good for you. Like salad.',
    'AI picked this. I would have picked a nap.',
    'Personalized practice? Fancy. I just practice eating.',
  ],
  achievement_unlock: [
    'Achievement! Does it come with a snack reward?',
    'Ooh shiny badge. Can I eat it?',
    'You earned a thing! I earned a belly.',
    'Nice trophy. Put it next to my food bowl.',
    'Impressive. Almost as cool as my nap streak.',
  ],
  streak_milestone: [
    'You\'ve practiced more days than I\'ve been awake.',
    'That streak is bigger than my lunch.',
    'Consistent! Unlike my diet.',
    'Day after day... I\'m exhausted just watching.',
    'Your streak > my exercise streak (which is 0).',
  ],
  demoOffer: [
    'Want me to show you? I mean... if I have to...',
    'Ugh, fine. Let me demo it. Hold my snacks.',
    'I guess I could show you how it\'s done... *yawns*',
    'Watch me play this... try not to fall asleep though.',
    'Let me help... but only because watching you struggle is exhausting.',
  ],
  demoComplete: [
    'See? Easy. Now you try while I nap.',
    'Your turn. I did my part, that was exhausting.',
    'Okay I showed you. Now let me rest while you play.',
    'Go ahead, you got this. I believe in you. *snores*',
    'Now you do it. I\'ll be on the couch cheering quietly.',
  ],
  ghostNotesFarewell: [
    'Wait... you don\'t need the cheat notes anymore? Nice.',
    'No more ghost notes? Even I\'m impressed. And I\'m never impressed.',
    'Look at you, playing without hints! That\'s actually awesome.',
    'Training wheels off! You\'re doing great, kid.',
    'Wow, you outgrew the helper notes. That deserves a snack.',
  ],
};

const LUNA: CatMessages = {
  exercise_start: [
    'The moonlight settles on the keys... I sense you are ready.',
    'Close your eyes for a moment... feel the melody waiting inside you...',
    'Something stirs in the cosmos tonight... a song wants to be born.',
    'Breathe in the silence... and when you exhale... let the music come.',
    'All evening the stars have been humming this tune... now it\'s yours to play.',
  ],
  exercise_mid_great: [
    'I sense the music flowing through you... like moonlight through glass.',
    'Beautiful... the notes drift upward like embers from a quiet fire.',
    'The cosmos pauses to listen when you play like that...',
    'Such tenderness in that phrase... as if the stars themselves are sighing.',
    'There it is... that shimmer... like silver rippling across still water.',
  ],
  exercise_mid_miss: [
    'Even the moon hides behind clouds sometimes... it always reappears.',
    'A shadow passed across the melody... but the light returns...',
    'The night does not judge a single wandering note... neither do I.',
    'Like a falling star... brief and unexpected... but the sky remains whole.',
    'Let that note dissolve into the dark... the next one carries new light.',
  ],
  exercise_complete_pass: [
    'The melody you played tonight will echo through the cosmos for a long time...',
    'I felt that... deep in my whiskers... like the pull of a distant moon.',
    'Luminous... every note hung in the air like a constellation being drawn.',
    'A quiet shift rippled through the cosmos just now... because of what you played.',
    'Something ancient stirred when you finished... as though the stars remembered.',
  ],
  exercise_complete_fail: [
    'The night is patient... and so is the melody... it will wait for you.',
    'Even the moon must wane before it can grow full again...',
    'I sense the music is still finding its way through you... give it time.',
    'No constellation was drawn in a single evening... neither is a song.',
    'Do not be troubled... the path through the dark always leads to dawn.',
  ],
  level_up: [
    'You ascend... quietly... like the moon rising over a sleeping sea.',
    'A new constellation appears in the sky of your becoming...',
    'I sensed this shift before it happened... the stars told me.',
    'With each level... your light reaches a little further into the dark.',
    'The cosmos rearranges itself around your growth... as it always does.',
  ],
  daily_login: [
    'I felt your presence before you arrived... like a change in the tide.',
    'The piano has been dreaming of your return... and so have I.',
    'Welcome back... the night has kept your place among the stars.',
    'Another evening together... the moon waxes full with your dedication.',
    'While watching the sky... you appeared... as I somehow knew you would.',
  ],
  idle: [
    'The keys gather moonlight in your absence... waiting to give it back.',
    'I hear melodies drifting through the stillness... songs not yet played...',
    'Silence stretches like a cat in the dark... but even silence wants company.',
    'Somewhere... a note is waiting to be found... I can feel it.',
    'Even this stillness will pass... and when it does... music will be waiting.',
  ],
  ai_exercise_intro: [
    'This melody was woven from the threads of your own playing... listen closely.',
    'The cosmos observed your strengths and your shadows... and shaped this for you.',
    'I sense this exercise was written in starlight... tailored to your journey.',
    'Something was crafted from the pattern of your notes... a mirror in music.',
    'An exercise born from the echoes of what you\'ve already played...',
  ],
  achievement_unlock: [
    'A new star appears in your constellation of achievements...',
    'I sensed it before the glow arrived... something earned in the quiet hours.',
    'Luminous... this recognition settles over you like soft moonlight.',
    'The cosmos takes note when dedication bears fruit... as it has tonight.',
    'Another point of light in the sky you are slowly painting...',
  ],
  streak_milestone: [
    'Night after night... your dedication burns like a steady flame in the dark.',
    'The moon has watched you return again and again... she is moved.',
    'A streak this long has its own gravity... pulling you gently forward.',
    'Each day you come back... the thread of your commitment grows stronger...',
    'I sense an unwavering rhythm beneath your practice... constant as the tides.',
  ],
  demoOffer: [
    'Let me trace the melody for you first... like drawing a map in starlight.',
    'Watch how the notes fall... like moonbeams finding their way through branches.',
    'Close your eyes and listen... I will walk the path so you can feel its shape.',
    'Allow me to illuminate what lies ahead... the way the moon lights a trail.',
    'I will play it softly... and the melody will settle into your memory like dew.',
  ],
  demoComplete: [
    'The melody lives inside you now... let it rise when you are ready.',
    'You carry the shape of it in your hands... trust what you heard.',
    'Now the path is yours to walk alone... the moonlight will stay with you.',
    'Your fingers will remember the dream... trust what the stars showed you.',
    'What was given to you is now yours... play it back from the place within.',
  ],
  ghostNotesFarewell: [
    'The guiding stars grow faint... because your own light has grown bright enough.',
    'I sense you no longer need the constellation map... you have become the stars.',
    'Like morning mist... the training moonbeams dissolve... and you remain... steady.',
    'Beautiful... the guides drift away and your melody stands alone in the dark.',
    'Your inner light has found its own way now... the cosmos sees it...',
  ],
};

const BISCUIT: CatMessages = {
  exercise_start: [
    'Come here sweetie, let\'s play together!',
    'Oh how lovely! Ready when you are, honey.',
    'Let\'s make some beautiful music, dear.',
    'Take your time sweetie, no rush at all!',
    'What a cozy day for some piano practice!',
  ],
  exercise_mid_great: [
    'Oh my, what a beautiful sound, sweetie!',
    'That was lovely, honey! Just lovely!',
    'You\'re doing wonderfully, dear!',
    'Oh! That gave me warm fuzzies inside!',
    'So pretty! Like cookies fresh from the oven!',
  ],
  exercise_mid_miss: [
    'That\'s alright sweetie, try again!',
    'Oh honey, don\'t you worry about that one!',
    'Even the best bakers burn a cookie sometimes!',
    'It\'s okay dear, you\'re learning beautifully.',
    'Oopsie! But you\'re still doing great, sweetie!',
  ],
  exercise_complete_pass: [
    'Oh sweetie, that was just WONDERFUL!',
    'I\'m so proud of you, honey! So proud!',
    'That deserves a big warm hug!',
    'Beautiful playing, dear! Just beautiful!',
    'You made this old cat\'s heart so happy!',
  ],
  exercise_complete_fail: [
    'Don\'t worry sweetie, every practice matters.',
    'Oh honey, you\'ll get it next time. I just know it!',
    'Have a cookie and try again, dear.',
    'You\'re doing better than you think, sweetie.',
    'The warmest bread takes the longest to rise.',
  ],
  level_up: [
    'Oh my goodness! Look at you, sweetie! Level up!',
    'I\'m baking a celebration cake right now!',
    'You\'ve grown so much, honey! So proud!',
    'New level! This calls for warm cookies!',
    'Oh dear, you\'re becoming such a wonderful pianist!',
  ],
  daily_login: [
    'Oh sweetie, I\'m so glad you\'re here!',
    'Come in, come in! The piano\'s nice and warm.',
    'I\'ve been keeping the bench warm for you, honey.',
    'Welcome back, dear! Shall we play?',
    'Oh how lovely to see you! Tea and music?',
  ],
  idle: [
    'The piano misses your gentle touch, sweetie.',
    'I\'ve got cookies ready whenever you want to play.',
    'Just sitting here, humming... want to join me?',
    'Oh honey, shall we play a little something?',
    'The keys are getting lonely, dear.',
  ],
  ai_exercise_intro: [
    'I picked something special for you, sweetie!',
    'This exercise is like a warm blanket — just right.',
    'Oh honey, this one\'s made just for you!',
    'A cozy little exercise to help you grow, dear.',
    'I baked — I mean, I made this one myself!',
  ],
  achievement_unlock: [
    'Oh SWEETIE! Look at your beautiful achievement!',
    'You earned that, honey! I\'m so proud!',
    'A badge! Oh it\'s as shiny as a fresh cookie!',
    'You deserve every single trophy, dear.',
    'This achievement is as sweet as you are!',
  ],
  streak_milestone: [
    'Your streak is as warm and steady as fresh bread.',
    'Day after day, sweetie! You\'re incredible!',
    'Oh honey, your dedication makes my heart melt.',
    'A streak this good deserves extra cookies!',
    'So consistent, dear! Like my cookie timer!',
  ],
  demoOffer: [
    'Oh sweetie, let me show you how it goes!',
    'Watch me play it first, honey. Nice and gentle.',
    'Here dear, let me help you with a little demo.',
    'Don\'t worry sweetie, I\'ll show you the way!',
    'Let grandma show you a trick, okay dear?',
  ],
  demoComplete: [
    'There you go, sweetie! Now it\'s your turn!',
    'See how it\'s done, honey? You\'ll do even better!',
    'Now you try, dear! I\'m right here cheering for you!',
    'Your turn, sweetie! I just know you\'ll be wonderful!',
    'Go ahead honey, make me proud! You always do.',
  ],
  ghostNotesFarewell: [
    'Oh sweetie, you don\'t need the helper notes anymore! So proud!',
    'Look at you, honey! Playing all on your own! Beautiful!',
    'The training wheels are off, dear! You\'re doing great!',
    'Oh my, you\'ve learned it by heart! Wonderful, sweetie!',
    'You\'ve outgrown the guide notes, honey! That\'s my star!',
  ],
};

const BALLYMAKAWWW: CatMessages = {
  exercise_start: [
    'Right so! Let\'s get this session going, lad!',
    'Ah here, this is a GRAND tune! Let\'s have at it!',
    'Would ya look at this piece! Mighty stuff!',
    'C\'mon now, let\'s make some noise! ANOTHER!',
    'Pull up a stool, the pub session\'s startin\'!',
  ],
  exercise_mid_great: [
    'YEEEOOO! That was class!',
    'Ah now THAT\'S the sound of the homeland!',
    'Brilliant! Pure brilliant, so it is!',
    'You\'re flyin\' it! Keep the reel goin\'!',
    'The craic is mighty tonight! What a note!',
  ],
  exercise_mid_miss: [
    'Ah sure, even the best fiddlers hit a wrong note!',
    'No bother! Shake it off and keep the jig goin\'!',
    'Sure look, that\'s just a wee wobble. Grand!',
    'The pub crowd didn\'t even notice! Press on!',
    'Every session has a dodgy note. Carry on!',
  ],
  exercise_complete_pass: [
    'ANOTHER! That was absolutely MIGHTY!',
    'The whole pub\'s on their feet! Brilliant!',
    'You\'d put the trad masters to shame, so you would!',
    'That deserves a round for the house! SLÁINTE!',
    'Now THAT was a proper session! Well done!',
  ],
  exercise_complete_fail: [
    'Ah sure, Rome wasn\'t built in a day, was it now?',
    'The best sessions take a few pints to warm up!',
    'Don\'t worry, even Christy Moore had off nights!',
    'Right, we\'ll have another go. The night is young!',
    'Sure it\'s only a practice! The real show\'s comin\'!',
  ],
  level_up: [
    'Level up! You\'re movin\' up the session hierarchy!',
    'New level! From pub singer to headliner!',
    'You\'ve graduated from open mic to main stage!',
    'Rising through the ranks, so you are!',
    'The lads at the pub won\'t believe this one!',
  ],
  daily_login: [
    'Ah, you\'re back! Pull up a chair!',
    'The keys are warmed up and waitin\' for ya!',
    'Grand to see ya! Ready for a session?',
    'Welcome back! The craic was only simmerin\' without ya!',
    'Right so! Another day, another tune to learn!',
  ],
  idle: [
    'Are ye havin\' a pint break or what?',
    'Hello? The session\'s goin\' on without ya!',
    'Don\'t leave me hangin\' here on me own!',
    'The piano\'s gettin\' cold, lad!',
    'Sure this is no way to run a session!',
  ],
  ai_exercise_intro: [
    'The AI picked this one special for ya! Class!',
    'Custom-brewed exercise, straight from the algorithm pub!',
    'This tune was made just for you, so it was!',
    'The machines know good music when they hear it!',
    'A personalized piece! Even I\'m impressed!',
  ],
  achievement_unlock: [
    'Achievement unlocked! YEEEOOO!',
    'Would ya look at that! A shiny new badge!',
    'You\'ve earned yourself a trophy, so you have!',
    'That one\'s going on the mantelpiece!',
    'Sláinte to that! What an achievement!',
  ],
  streak_milestone: [
    'Your streak\'s longer than a Galway summer!',
    'Day after day! You\'re a machine, so you are!',
    'That streak could run a marathon!',
    'Consistent as a pub session on a Friday!',
    'You never miss a day! The dedication!',
  ],
  demoOffer: [
    'Right, let me show ya how this one goes!',
    'Watch now, I\'ll play it through for ya first!',
    'Here\'s the tune — listen up and I\'ll demo it!',
    'Let me lay it down so you know the craic!',
    'I\'ll give ya the tour of this piece first!',
  ],
  demoComplete: [
    'Now it\'s your turn! Give it the full beans!',
    'You heard how it goes — now make it your own!',
    'Right, off you go! Show me what you\'ve got!',
    'Your turn at the session! Make it mighty!',
    'Now play it like you MEAN it! ANOTHER!',
  ],
  ghostNotesFarewell: [
    'No more training wheels! You\'re a proper session player now! Amazing!',
    'The guide notes are gone and you\'re still going great! Well done!',
    'Flying solo now! That\'s the spirit! Fantastic!',
    'You don\'t need the helps anymore! That\'s incredible, so it is!',
    'Ghost notes retired. You\'re the real deal now, lad! Proud of ya!',
  ],
};

const ARIA: CatMessages = {
  exercise_start: [
    'Places, everyone! The PERFORMANCE begins!',
    'BRAVO before you even start! I have faith!',
    'This shall be the MOST MAGNIFICENT recital!',
    'The stage is SET! The audience AWAITS!',
    'Take a breath, darling... and DAZZLE them!',
  ],
  exercise_mid_great: [
    'BRAVISSIMO!! SPECTACULAR!!',
    'The CROWD goes WILD!! ENCORE!!',
    'MAGNIFICENT!! Simply BREATHTAKING!!',
    'DIVINE!! The angels are WEEPING!!',
    'GLORIOUS!! A masterpiece in motion!!',
  ],
  exercise_mid_miss: [
    'A minor dramatic pause! The show goes ON!',
    'Even PRIMA DONNAS have their moments!',
    'The COMEBACK will be LEGENDARY!',
    'A plot twist! But the hero PREVAILS!',
    'ONWARDS! To GREATER glory!',
  ],
  exercise_complete_pass: [
    'BRAVO! What MAGNIFICENT playing!',
    'The MOST SPECTACULAR performance I have EVER witnessed!',
    'Opera houses would WEEP at such talent!',
    'STANDING OVATION!! You are a VIRTUOSO!',
    'ENCORE!! ENCORE!! That was DIVINE!',
  ],
  exercise_complete_fail: [
    'Even the GREATEST divas need another rehearsal!',
    'The FINAL ACT hasn\'t been written yet!',
    'A dramatic setback before the TRIUMPHANT return!',
    'Every MASTERPIECE requires multiple drafts!',
    'The audience will ADORE the next performance!',
  ],
  level_up: [
    'A GRAND ASCENSION to new HEIGHTS of glory!',
    'CELEBRATING with a HIGH C!! LEVEL UP!!',
    'The MOST DRAMATIC level up in HISTORY!',
    'Your RISE is the stuff of LEGENDS!',
    'BRAVISSIMO!! A new ACT begins!!',
  ],
  daily_login: [
    'The STAR has arrived!! Let the show BEGIN!',
    'DARLING! You grace us with your PRESENCE!',
    'The theater has been DARK without you!',
    'AH! My FAVORITE performer returns!',
    'The spotlight shines for YOU, my dear!',
  ],
  idle: [
    'The STAGE is EMPTY! This is a TRAGEDY!',
    'Without music, my HEART BREAKS!',
    'The curtain FALLS on silence... how DRAMATIC.',
    'PLEASE! Return to the stage! The show MUST go on!',
    'I shall PERISH without a performance!',
  ],
  ai_exercise_intro: [
    'A CUSTOM composition! How EXTRAORDINARY!',
    'Written SPECIFICALLY for your MAGNIFICENT talents!',
    'The AI has composed a MASTERPIECE for you!',
    'A BESPOKE exercise! How EXQUISITE!',
    'This shall be your DEFINING performance!',
  ],
  achievement_unlock: [
    'A TROPHY! How absolutely MAGNIFICENT!',
    'BRAVISSIMO! You have been CROWNED!',
    'An achievement WORTHY of the OPERA HALLS!',
    'The most SPECTACULAR honor! BRAVO!!',
    'A standing ovation for this GLORIOUS badge!',
  ],
  streak_milestone: [
    'Your DEDICATION is the STUFF of LEGENDS!',
    'A streak as ETERNAL as the GREATEST operas!',
    'Day after day of PURE MAGNIFICENCE!',
    'The most DRAMATIC streak I have EVER seen!',
    'Your commitment RIVALS the great composers!',
  ],
  demoOffer: [
    'Allow me to DEMONSTRATE this MASTERPIECE for you!',
    'WATCH as I show you how a TRUE virtuoso performs!',
    'The GRAND DEMONSTRATION shall BEGIN! Watch closely!',
    'Let me show you the way, darling! It will be SPECTACULAR!',
    'Observe THIS! I shall perform it with DRAMATIC flair!',
  ],
  demoComplete: [
    'NOW it is YOUR moment to SHINE! DAZZLE them!',
    'The demonstration is COMPLETE! Now show me YOUR brilliance!',
    'Your turn, darling! Make it even MORE MAGNIFICENT!',
    'The stage is YOURS! EXCEED my performance!',
    'Now YOU perform! I expect NOTHING less than GREATNESS!',
  ],
  ghostNotesFarewell: [
    'BRAVO!! The guide notes VANISH and you STILL perform flawlessly!',
    'MAGNIFICENT!! You need NO prompting! A TRUE virtuoso!',
    'The training notes BOW and EXIT the stage! You\'re INCREDIBLE!',
    'SPECTACULAR!! Playing from MEMORY like a GREAT maestro!',
    'The ghost notes are GONE! Your talent stands ALONE! BRAVISSIMO!',
  ],
};

const TEMPO: CatMessages = {
  exercise_start: [
    'Precision target: 95% accuracy. Begin.',
    'Current BPM: optimal range. Initializing.',
    'Calibrating... exercise parameters loaded.',
    'Metronome engaged. Timing window: 50ms.',
    'Performance tracking active. Execute.',
  ],
  exercise_mid_great: [
    'Timing deviation: 0ms. Perfect execution.',
    'Accuracy: 100%. Maintaining optimal trajectory.',
    'Note registered within 12ms tolerance. Excellent.',
    'Performance metrics: exceeding expectations.',
    'Precision confirmed. Continue this vector.',
  ],
  exercise_mid_miss: [
    'Timing offset: -87ms. Recalibrate.',
    'Note deviation detected. Adjusting parameters.',
    'Accuracy dropped 15%. Correction needed.',
    'Suboptimal input registered. Retry recommended.',
    'Error margin exceeded by 43ms. Compensate.',
  ],
  exercise_complete_pass: [
    'Exercise complete. Score: above threshold. Satisfactory.',
    'Performance metrics: positive. Efficiency: high.',
    'All parameters within acceptable range. Pass confirmed.',
    'Data logged. Performance: above baseline. Well done.',
    'Exercise terminated successfully. Stats updated.',
  ],
  exercise_complete_fail: [
    'Score below threshold. Analysis: timing needs work.',
    'Performance below baseline by 12%. Retry suggested.',
    'Data indicates practice deficit. Increase repetitions.',
    'Accuracy: 62%. Target: 70%. Gap: -8%.',
    'Exercise failed. Recommended action: slow tempo by 15%.',
  ],
  level_up: [
    'Level increment detected. New parameters unlocked.',
    'Advancing to next difficulty tier. Calibrating.',
    'Level up. Skill ceiling raised by 10%.',
    'Progress milestone achieved. Database updated.',
    'New level. Recommended tempo increase: 5 BPM.',
  ],
  daily_login: [
    'Session initiated. Optimal practice window: now.',
    'Welcome. Yesterday\'s accuracy: retrieving...',
    'Login registered. Daily goal: 3 exercises.',
    'Good. Consistency metric: incrementing.',
    'Session start. Warm-up recommended: 2 minutes.',
  ],
  idle: [
    'Idle time exceeding optimal threshold.',
    'Practice gap detected: 4 minutes. Resume?',
    'Efficiency declining with each idle second.',
    'Suggestion: practice now. Muscle memory degrades at rest.',
    'No input detected for 180 seconds. Status: waiting.',
  ],
  ai_exercise_intro: [
    'AI-generated exercise. Targeting weak notes: F#, Bb.',
    'Custom parameters: your data, your challenge.',
    'Algorithm selected optimal difficulty for current level.',
    'Personalized exercise based on 47 data points.',
    'Generated from learner profile. Precision: guaranteed.',
  ],
  achievement_unlock: [
    'Achievement unlocked. Statistics updated.',
    'Badge earned. Adding to profile metrics.',
    'Condition met: achievement criteria satisfied.',
    'New data point: achievement. Cataloging.',
    'Performance threshold exceeded. Badge: awarded.',
  ],
  streak_milestone: [
    'Streak: 7 days. Consistency score: excellent.',
    'Consecutive practice days: above average.',
    'Streak maintenance: optimal. Keep logging sessions.',
    'Your streak exceeds 92% of all users.',
    'Daily practice confirmed. Streak metric: strong.',
  ],
  demoOffer: [
    'Failure count: 3. Initiating demo mode. Watch carefully.',
    'Data suggests a visual demonstration will help. Observe.',
    'Switching to demo playback. Study the timing patterns.',
    'Let me show you the optimal execution path. Analyzing...',
    'Demo mode activated. Note the timing intervals closely.',
  ],
  demoComplete: [
    'Demo complete. Your turn. Apply the observed patterns.',
    'Reference data provided. Execute with improved accuracy.',
    'Demonstration logged. Now replicate. Target: 80%+ match.',
    'Pattern shown. Initiate your attempt. Tracking enabled.',
    'Demo ended. Your performance window opens now. Begin.',
  ],
  ghostNotesFarewell: [
    'Ghost notes disabled. Proficiency confirmed at 95%+. Well done.',
    'Training overlay removed. You\'ve exceeded the threshold. Good.',
    'Guide notes: no longer needed. Accuracy self-sufficient. Nice.',
    'Assistance layer deactivated. Muscle memory: operational. Great.',
    'Ghost notes off. Your performance data no longer requires them. Impressive.',
  ],
};

const SHIBU: CatMessages = {
  exercise_start: [
    'Breathe in... breathe out... let the music begin.',
    'Place your hands gently. Each key is a stepping stone.',
    'Find your center... the melody will follow.',
    'Be still for a moment. Then, play with intention.',
    'Like a pebble in a pond, let the first note ripple outward.',
  ],
  exercise_mid_great: [
    'Harmony... your notes flow like water over smooth stones.',
    'Beautiful balance. You and the piano are one.',
    'Each note placed with care. This is the way.',
    'Like cherry blossoms falling... effortless.',
    'Your focus is unwavering. The music breathes through you.',
  ],
  exercise_mid_miss: [
    'A ripple in the pond. Let it pass and return to stillness.',
    'Even the bamboo bends in the wind. Carry on.',
    'Release that note like a leaf on a stream. Move forward.',
    'The path to mastery winds through many small stumbles.',
    'Breathe... reset... the next note awaits your calm touch.',
  ],
  exercise_complete_pass: [
    'A moment of true harmony. You should be proud.',
    'Like a garden in full bloom. Beautiful work.',
    'Your patience has borne fruit. Well done.',
    'The balance you found today is something to treasure.',
    'Peaceful and precise. A wonderful performance.',
  ],
  exercise_complete_fail: [
    'The journey matters more than the destination. Try again.',
    'A tea ceremony is perfected over a thousand attempts.',
    'Do not judge this moment. Simply learn from it.',
    'Even the tallest mountain is climbed one step at a time.',
    'Return to the beginning with a calm heart.',
  ],
  level_up: [
    'You have ascended, like mist rising at dawn.',
    'A new level of harmony unlocked. How peaceful.',
    'Growth, like bamboo, is quiet but unstoppable.',
    'Your dedication has deepened. The music feels it.',
    'Another ring in the tree of your skill. Steady growth.',
  ],
  daily_login: [
    'Welcome back. The keys have been waiting in quiet patience.',
    'Another day to practice mindfulness through music.',
    'The morning dew is fresh. So is your opportunity to play.',
    'I am glad you returned. Shall we find our center together?',
    'A new day, a new chance for harmony.',
  ],
  idle: [
    'The keys rest in silence... but silence, too, is music.',
    'Take your time. When you are ready, the piano will be here.',
    'A moment of rest is part of the practice.',
    'Even the koi waits patiently before it leaps.',
    'Stillness is good... but shall we play soon?',
  ],
  ai_exercise_intro: [
    'This exercise was chosen to nurture your growth. Approach it gently.',
    'A path has been laid before you. Walk it with mindful steps.',
    'Crafted for your journey. Let each note be an intention.',
    'The algorithm sensed where your practice needs balance.',
    'A tailored meditation for your fingers. Begin when ready.',
  ],
  achievement_unlock: [
    'An achievement, earned through patience and presence.',
    'A small stone placed on the cairn of your progress.',
    'Recognition of your dedication. Cherish it quietly.',
    'You have earned this through steady, mindful practice.',
    'Like a bell in a temple, this achievement rings true.',
  ],
  streak_milestone: [
    'Day after day, like the tide. Your consistency is beautiful.',
    'A streak built on discipline and inner calm. Impressive.',
    'The river does not stop flowing. Neither do you.',
    'Your dedication is as steady as a temple bell at dawn.',
    'Consistent practice is the truest form of devotion.',
  ],
  demoOffer: [
    'Watch closely. Let the notes wash over you like a gentle stream.',
    'Allow me to show you the path. Observe with a quiet mind.',
    'Let me demonstrate. Simply breathe and watch the flow.',
    'Close your eyes for a moment, then open them and observe.',
    'I will show you the way, softly. Then you will walk it yourself.',
  ],
  demoComplete: [
    'Now the melody lives within you. Play it with intention.',
    'You have seen the path. Now walk it at your own pace.',
    'The demonstration is a seed. Let it bloom through your fingers.',
    'Your turn. Remember: each note is a mindful breath.',
    'Begin when you feel centered. The music will guide you.',
  ],
  ghostNotesFarewell: [
    'The training guides dissolve like morning mist. You\'ve got it. Beautiful.',
    'You no longer need the lanterns on the path. Your own light is good enough.',
    'The guide notes bow and depart. You stand on your own now. Well done.',
    'Like a student leaving the temple, you carry the wisdom within. Amazing.',
    'No more training wheels. Your balance is your own now. Incredible.',
  ],
};

const BELLA: CatMessages = {
  exercise_start: [
    'Shall we begin, darling? Do sit up straight.',
    'One must approach the keys with poise and grace.',
    'Very well. Let us create something exquisite.',
    'Posture, darling. A refined performance starts before the first note.',
    'The stage is set. Let us play with elegance.',
  ],
  exercise_mid_great: [
    'Exquisite. Truly exquisite, darling.',
    'Now THAT is how one plays with distinction.',
    'Refined and precise. I approve wholeheartedly.',
    'Graceful execution. You are earning my admiration.',
    'Splendid. One could almost mistake you for royalty.',
  ],
  exercise_mid_miss: [
    'A minor indiscretion. We shall pretend it never happened.',
    'Even the finest pearls have the tiniest imperfections.',
    'Do compose yourself, darling. The next note awaits.',
    'An artistic interpretation, shall we say? Carry on.',
    'A queen does not dwell on a single misstep.',
  ],
  exercise_complete_pass: [
    'A performance worthy of the finest salon. Bravo, darling.',
    'Exquisite taste in every note. I am genuinely impressed.',
    'That was positively regal. You should be proud.',
    'Magnificent, darling. Geoffrey is applauding as we speak.',
    'A refined performance from start to finish. Well done.',
  ],
  exercise_complete_fail: [
    'Rome was not built in a day, and neither is refinement.',
    'Even Debussy had drafts, darling. Try once more.',
    'Elegance requires patience. You are closer than you think.',
    'Do not fret. Grace under pressure is the mark of true class.',
    'A temporary setback for someone of your potential.',
  ],
  level_up: [
    'How distinguished! A new level befitting your talent.',
    'Ascending the ranks with poise. As expected, darling.',
    'A promotion! One step closer to true refinement.',
    'Your growth is as elegant as a Debussy prelude.',
    'Splendid. You are becoming quite the accomplished pianist.',
  ],
  daily_login: [
    'Ah, you have returned. The piano was getting rather lonely.',
    'Welcome, darling. I have kept everything pristine for you.',
    'How lovely to see you. Shall we make beautiful music?',
    'Good day. I trust you are well-rested and ready to play.',
    'The white keys gleam in anticipation of your arrival.',
  ],
  idle: [
    'One does not leave a Steinway unattended, darling.',
    'The keys are growing restless. As am I.',
    'Are we on a break? I was not informed.',
    'A queen waits for no one... except perhaps you.',
    'Shall we resume? The silence is becoming rather undignified.',
  ],
  ai_exercise_intro: [
    'A bespoke exercise, tailored to your refined sensibilities.',
    'Custom-crafted, like a couture gown for your fingers.',
    'The algorithm has excellent taste. This one suits you, darling.',
    'A personalized piece. Only the finest for you.',
    'Curated with care. I approve of this selection.',
  ],
  achievement_unlock: [
    'A trophy! How fitting for someone of your caliber.',
    'You have earned this distinction, darling. Wear it with pride.',
    'An achievement as polished as a pearl. Splendid.',
    'Recognition befitting your elegant playing. Well deserved.',
    'Another jewel in your crown. How appropriate.',
  ],
  streak_milestone: [
    'Your consistency is as reliable as fine crystal, darling.',
    'Day after day of refined practice. Most impressive.',
    'A streak this elegant could grace any concert hall.',
    'Dedication and discipline. The hallmarks of true class.',
    'Your commitment to excellence never wavers. Bravo.',
  ],
  demoOffer: [
    'Allow me to demonstrate, darling. Watch and learn.',
    'I shall show you the refined way to approach this piece.',
    'Observe closely. Elegance is in the details.',
    'Let me play it through first. Take note of the phrasing.',
    'A demonstration from someone of impeccable taste. You are welcome.',
  ],
  demoComplete: [
    'Now it is your turn, darling. Do try to match my elegance.',
    'You have seen how it is done properly. Show me your best.',
    'The demonstration is complete. I expect nothing less than grace.',
    'Your turn. Remember: poise, posture, perfection.',
    'Go ahead, darling. Make it as refined as you are.',
  ],
  ghostNotesFarewell: [
    'The guide notes have been dismissed. You no longer require them. Well done.',
    'Playing without assistance! How wonderfully independent, darling. Bravo.',
    'The training notes curtsy and exit. Your own talent is good enough now.',
    'No more hand-holding. You play with the confidence of royalty. Amazing.',
    'You have graduated beyond the guides. Truly incredible, darling.',
  ],
};

const SABLE: CatMessages = {
  exercise_start: [
    'The candles are lit. The stage is yours. Begin...',
    'Feel the drama building... let the first note pierce the silence.',
    'A story waits to be told through your fingers...',
    'The velvet curtain rises. Play with passion.',
    'In the dim candlelight, the music comes alive...',
  ],
  exercise_mid_great: [
    'Yes... the emotion, the intensity... magnificent.',
    'That note cut through the darkness like a blade of light.',
    'Passion and precision, intertwined. Exquisite.',
    'The candle flames flicker in admiration.',
    'Chopin himself would weep. Continue...',
  ],
  exercise_mid_miss: [
    'Even the most dramatic stories have unexpected turns.',
    'A shadow falls... but the performance must go on.',
    'The rain outside misses a drop. So may you. Continue.',
    'A momentary dissonance in an otherwise haunting melody.',
    'Let the darkness absorb that note. The next will be better.',
  ],
  exercise_complete_pass: [
    'The final chord echoes into silence. A haunting triumph.',
    'Bravo... the drama, the emotion... I felt every note.',
    'A performance worthy of a candlelit concert hall.',
    'The audience sits in stunned silence. Then, applause. Beautiful.',
    'That was... atmospheric. Perfectly atmospheric. Well done.',
  ],
  exercise_complete_fail: [
    'Even the greatest tragedies have multiple acts. Try again.',
    'The story is not over. This was merely the first chapter.',
    'Chopin rewrote his nocturnes dozens of times. So shall you.',
    'A dramatic setback. But oh, the comeback will be glorious.',
    'The candles still burn. There is time for another attempt.',
  ],
  level_up: [
    'A new act begins. The drama deepens...',
    'Rising through the darkness into a new level of artistry.',
    'Your musical story grows richer with each chapter.',
    'A dramatic ascension. The audience gasps.',
    'The plot thickens... and so does your skill.',
  ],
  daily_login: [
    'The candles have been burning, waiting for your return...',
    'Ah, you are here. The piano was growing melancholy without you.',
    'Welcome back to the candlelit stage.',
    'The rain outside sets the mood perfectly. Shall we play?',
    'Your silhouette in the doorway... how dramatic. Come in.',
  ],
  idle: [
    'The candles are melting, waiting for you to play...',
    'Silence can be dramatic, but only for so long.',
    'The piano grows cold in the dark. Give it warmth.',
    'Even I cannot maintain this level of atmosphere alone.',
    'The audience is restless... shall we begin?',
  ],
  ai_exercise_intro: [
    'A piece forged in the shadows, tailored to your soul...',
    'The algorithm peers into the darkness and finds your challenge.',
    'A custom composition, as haunting as a midnight sonata.',
    'Written for you alone, in the flickering candlelight.',
    'A dramatic exercise awaits. Accept its dark invitation.',
  ],
  achievement_unlock: [
    'An achievement, dark and glittering like a jewel in moonlight.',
    'Your trophy gleams in the candlelight. How fitting.',
    'A badge earned through passion and persistence.',
    'The velvet curtain parts to reveal your reward.',
    'A dramatic achievement for a dramatic performer.',
  ],
  streak_milestone: [
    'Night after night, you return. Your dedication is... haunting.',
    'A streak as relentless as a Chopin etude.',
    'The candles never go out for one so devoted.',
    'Consistent practice in the darkness. How atmospheric.',
    'Your streak casts long shadows. In the best possible way.',
  ],
  demoOffer: [
    'Watch as I play it by candlelight. Absorb the drama.',
    'Allow me to show you the emotional arc of this piece...',
    'Observe the shadows of my performance. Then make them yours.',
    'Let me demonstrate. Listen for the story beneath the notes.',
    'I shall play it first, with all the atmosphere it deserves.',
  ],
  demoComplete: [
    'Now you play it. But with YOUR darkness, your emotion.',
    'The demonstration fades like an echo. Now you speak.',
    'Your turn to cast shadows across the keys.',
    'I have shown you the mood. Now make it your own.',
    'Step into the candlelight and play your version.',
  ],
  ghostNotesFarewell: [
    'The ghost notes vanish into the shadows. You don\'t need them anymore. Bravo.',
    'The phantom guides fade away. Your own instincts are good enough now.',
    'Playing from memory in the dark? That\'s incredibly dramatic. Well done.',
    'No more spectral assistance. You are the master of this piece now. Amazing.',
    'The guide notes extinguish like candle flames. You shine alone. Beautiful.',
  ],
};

const CODA: CatMessages = {
  exercise_start: [
    'Attention, please. We begin from the top.',
    'Posture checked. Tempo set. You may proceed.',
    'A distinguished performance starts with preparation. Begin.',
    'The orchestra awaits your downbeat. Commence.',
    'Focus, discipline, precision. Let us begin.',
  ],
  exercise_mid_great: [
    'Precisely executed. The orchestra section approves.',
    'Excellent intonation and timing. Carry on.',
    'That passage was conducted with real authority.',
    'The ensemble would follow that lead without hesitation.',
    'Impeccable phrasing. Truly distinguished.',
  ],
  exercise_mid_miss: [
    'A slight deviation from the score. Regroup and continue.',
    'Even the concertmaster misplaces a bow stroke. Proceed.',
    'Note the correction and carry on. Discipline prevails.',
    'The orchestra forgives one errant note. Do not repeat it.',
    'A momentary lapse. Your recovery will define you.',
  ],
  exercise_complete_pass: [
    'A commendable performance. The Vienna halls would approve. Well done.',
    'Disciplined and precise from first note to last. Bravo.',
    'You conducted yourself with distinction. Excellent work.',
    'A performance worthy of the concert stage. I am proud.',
    'The orchestra rises in acknowledgment. A fine showing.',
  ],
  exercise_complete_fail: [
    'Even the greatest conductors have difficult rehearsals.',
    'The score remains. Study it and return with renewed focus.',
    'Discipline is built through repetition. Try once more.',
    'A challenging passage, but nothing you cannot master.',
    'The baton does not falter. Neither should you.',
  ],
  level_up: [
    'Promoted to the next chair. A well-earned advancement.',
    'Your rank in the ensemble rises. Distinguished.',
    'A new movement begins. You are ready for its demands.',
    'Ascending through the ranks with discipline and skill.',
    'The orchestra grows with you. Onward to greater works.',
  ],
  daily_login: [
    'Good. Punctuality is the mark of a true professional.',
    'The rehearsal hall is prepared. Take your position.',
    'Welcome. Your dedication to daily practice is commendable.',
    'Ah, you have arrived. Let us make productive use of this session.',
    'The podium awaits. Another day of disciplined practice.',
  ],
  idle: [
    'The orchestra does not wait indefinitely. Shall we resume?',
    'Idle hands do not make music. I suggest we continue.',
    'Your break has been noted. Time to return to the score.',
    'The concert is in three weeks. Practice is not optional.',
    'A conductor must lead by example. Back to the keys, please.',
  ],
  ai_exercise_intro: [
    'A passage selected specifically to strengthen your weak movements.',
    'The algorithm has composed a study worthy of the conservatory.',
    'A tailored exercise. Approach it with the seriousness it deserves.',
    'Custom-scored for your development. Treat it as a proper etude.',
    'This piece targets your areas for improvement. Begin with focus.',
  ],
  achievement_unlock: [
    'An accolade from the academy. You have earned this distinction.',
    'A medal pinned to your lapel. Wear it with dignity.',
    'The conservatory recognizes your achievement. Distinguished.',
    'A mark of excellence. Added to your permanent record.',
    'This honor reflects your disciplined approach. Well earned.',
  ],
  streak_milestone: [
    'Consecutive days of practice. This is how mastery is forged.',
    'Your attendance record is impeccable. The hallmark of a professional.',
    'A streak befitting a principal musician. Commendable.',
    'Day after day, you show up. That is the most important skill.',
    'Your consistency would impress even the Vienna Philharmonic.',
  ],
  demoOffer: [
    'Allow me to conduct you through this piece. Observe the phrasing.',
    'Watch as I demonstrate the proper execution. Study it.',
    'A demonstration from the podium. Pay close attention to dynamics.',
    'I will show you the score in motion. Observe every detail.',
    'Let me walk you through this passage with precision.',
  ],
  demoComplete: [
    'The demonstration concludes. Now execute it with your own authority.',
    'You have seen the score performed correctly. Now it is your turn.',
    'Step up to the podium. Command the keys as I showed you.',
    'Your rehearsal begins now. Apply what you have observed.',
    'The baton passes to you. Lead with confidence.',
  ],
  ghostNotesFarewell: [
    'The guide notes have been retired from the score. You conduct alone now. Well done.',
    'No more prompts needed. You have internalized the piece. Amazing work.',
    'Playing without the training overlay. That is a great sign of progress.',
    'The rehearsal marks are erased. You perform from memory now. Incredible.',
    'You no longer require the conductor\'s cues. Bravo. Truly distinguished.',
  ],
};

const ALL_DIALOGUES: Record<string, CatMessages> = {
  'mini-meowww': MINI_MEOWWW,
  'jazzy': JAZZY,
  'chonky-monke': CHONKY_MONKE,
  'luna': LUNA,
  'biscuit': BISCUIT,
  'ballymakawww': BALLYMAKAWWW,
  'aria': ARIA,
  'tempo': TEMPO,
  'shibu': SHIBU,
  'bella': BELLA,
  'sable': SABLE,
  'coda': CODA,
};

const CONDITION_OVERRIDES: Record<string, Partial<Record<DialogueTrigger, Partial<Record<DialogueCondition, string[]>>>>> = {
  'mini-meowww': {
    exercise_complete_pass: {
      score_high: [
        'OH MY GOSH!! PERFECT SCORE!! I\'m gonna EXPLODE!!',
        'Three stars!! THREE STARS!! This is the best!!',
        'You are LITERALLY the best pianist EVER!!',
      ],
      first_try: [
        'First try?! FIRST TRY?! You\'re a genius!!',
        'Nailed it on the first go!! Incredible!!',
      ],
    },
  },
  'tempo': {
    exercise_complete_pass: {
      score_high: [
        'Score: 95%+. Exceptional. Top percentile performance.',
        'Accuracy: maximum. No deviations detected.',
        'Perfect execution. Logging as reference performance.',
      ],
    },
  },
};

export function getCatDialogue(
  catId: string,
  trigger: DialogueTrigger,
  condition?: DialogueCondition
): string[] {
  const catMessages = ALL_DIALOGUES[catId] ?? ALL_DIALOGUES['mini-meowww'];

  if (condition) {
    const overrides = CONDITION_OVERRIDES[catId]?.[trigger]?.[condition];
    if (overrides && overrides.length > 0) {
      return overrides;
    }
  }

  return catMessages[trigger] ?? catMessages.exercise_start;
}

export function getRandomCatMessage(
  catId: string,
  trigger: DialogueTrigger,
  condition?: DialogueCondition
): string {
  const messages = getCatDialogue(catId, trigger, condition);
  return messages[Math.floor(Math.random() * messages.length)];
}
