/**
 * AUTO-GENERATED by scripts/generate-content-registry.ts
 * Do not edit manually. Run: npx tsx scripts/generate-content-registry.ts
 * Generated: 2026-03-11T11:04:40.480Z
 * Exercises: 36
 */

import type { Exercise } from '../core/exercises/types';

type ExerciseLoader = () => Exercise;

const EXERCISE_LOADERS: Record<string, ExerciseLoader> = {
  'lesson-01-ex-01': () => require('../../content/exercises/lesson-01/exercise-01-find-middle-c.json') as Exercise,
  'lesson-01-ex-02': () => require('../../content/exercises/lesson-01/exercise-02-keyboard-geography.json') as Exercise,
  'lesson-01-ex-03': () => require('../../content/exercises/lesson-01/exercise-03-white-keys.json') as Exercise,
  'lesson-01-test': () => require('../../content/exercises/lesson-01/exercise-test.json') as Exercise,
  'lesson-02-ex-01': () => require('../../content/exercises/lesson-02/exercise-01-cde-simple.json') as Exercise,
  'lesson-02-ex-02': () => require('../../content/exercises/lesson-02/exercise-02-cdefg.json') as Exercise,
  'lesson-02-ex-03': () => require('../../content/exercises/lesson-02/exercise-03-c-major-octave.json') as Exercise,
  'lesson-02-ex-04': () => require('../../content/exercises/lesson-02/exercise-04-mary-snippet.json') as Exercise,
  'lesson-02-ex-05': () => require('../../content/exercises/lesson-02/exercise-05-broken-c-chord.json') as Exercise,
  'lesson-02-ex-06': () => require('../../content/exercises/lesson-02/exercise-06-twinkle-twinkle.json') as Exercise,
  'lesson-02-ex-07': () => require('../../content/exercises/lesson-02/exercise-07-eighth-note-drill.json') as Exercise,
  'lesson-02-ex-08': () => require('../../content/exercises/lesson-02/exercise-08-c-position-review.json') as Exercise,
  'lesson-02-test': () => require('../../content/exercises/lesson-02/exercise-test.json') as Exercise,
  'lesson-03-ex-01': () => require('../../content/exercises/lesson-03/exercise-01-left-c-position.json') as Exercise,
  'lesson-03-ex-02': () => require('../../content/exercises/lesson-03/exercise-02-left-scale-down.json') as Exercise,
  'lesson-03-ex-03': () => require('../../content/exercises/lesson-03/exercise-03-bass-notes.json') as Exercise,
  'lesson-03-ex-04': () => require('../../content/exercises/lesson-03/exercise-04-broken-f-chord-left.json') as Exercise,
  'lesson-03-ex-05': () => require('../../content/exercises/lesson-03/exercise-05-steady-bass-pattern.json') as Exercise,
  'lesson-03-test': () => require('../../content/exercises/lesson-03/exercise-test.json') as Exercise,
  'lesson-04-ex-01': () => require('../../content/exercises/lesson-04/exercise-01-hands-melody-bass.json') as Exercise,
  'lesson-04-ex-02': () => require('../../content/exercises/lesson-04/exercise-02-mary-full-version.json') as Exercise,
  'lesson-04-ex-03': () => require('../../content/exercises/lesson-04/exercise-03-hand-independence-drill.json') as Exercise,
  'lesson-04-ex-04': () => require('../../content/exercises/lesson-04/exercise-04-ode-to-joy-intro.json') as Exercise,
  'lesson-04-ex-05': () => require('../../content/exercises/lesson-04/exercise-05-blocked-c-f-chords.json') as Exercise,
  'lesson-04-ex-06': () => require('../../content/exercises/lesson-04/exercise-06-both-hands-review.json') as Exercise,
  'lesson-04-test': () => require('../../content/exercises/lesson-04/exercise-test.json') as Exercise,
  'lesson-05-ex-01': () => require('../../content/exercises/lesson-05/exercise-01-scale-technique.json') as Exercise,
  'lesson-05-ex-02': () => require('../../content/exercises/lesson-05/exercise-02-parallel-scales.json') as Exercise,
  'lesson-05-ex-03': () => require('../../content/exercises/lesson-05/exercise-03-scale-speed-drill.json') as Exercise,
  'lesson-05-ex-04': () => require('../../content/exercises/lesson-05/exercise-04-scale-review.json') as Exercise,
  'lesson-05-test': () => require('../../content/exercises/lesson-05/exercise-test.json') as Exercise,
  'lesson-06-ex-01': () => require('../../content/exercises/lesson-06/exercise-01-jingle-bells.json') as Exercise,
  'lesson-06-ex-02': () => require('../../content/exercises/lesson-06/exercise-02-happy-birthday.json') as Exercise,
  'lesson-06-ex-03': () => require('../../content/exercises/lesson-06/exercise-03-amazing-grace.json') as Exercise,
  'lesson-06-ex-04': () => require('../../content/exercises/lesson-06/exercise-04-let-it-go-snippet.json') as Exercise,
  'lesson-06-test': () => require('../../content/exercises/lesson-06/exercise-test.json') as Exercise,
};

/**
 * Load an exercise by ID. Returns null if not found.
 * The require() is deferred until this function is called (lazy loading).
 */
export function loadExerciseFromRegistry(id: string): Exercise | null {
  const loader = EXERCISE_LOADERS[id];
  return loader ? loader() : null;
}

/** Get all registered exercise IDs */
export function getRegisteredExerciseIds(): string[] {
  return Object.keys(EXERCISE_LOADERS);
}

/** Total number of registered exercises */
export const REGISTERED_EXERCISE_COUNT = 36;
