/**
 * Generate Content Registry
 *
 * Scans content/exercises/lesson-*\/ directories for JSON files and generates
 * a TypeScript file with lazy-loading thunks for all exercises.
 *
 * Metro bundler requires static require() strings — this script generates them
 * at build time so the ContentLoader can lazy-load exercises without needing
 * dynamic imports.
 *
 * Usage: npx tsx scripts/generate-content-registry.ts [--dry-run] [--verbose]
 */

import { readFileSync, writeFileSync, readdirSync, existsSync } from 'fs';
import { join, resolve } from 'path';

// ---------------------------------------------------------------------------
// Config
// ---------------------------------------------------------------------------

const ROOT = resolve(__dirname, '..');
const EXERCISES_DIR = join(ROOT, 'content', 'exercises');
const OUTPUT_PATH = join(ROOT, 'src', 'content', 'ContentLoaderRegistry.generated.ts');

/** Relative path from src/content/ to content/exercises/ */
const REQUIRE_PREFIX = '../../content/exercises';

const args = process.argv.slice(2);
const DRY_RUN = args.includes('--dry-run');
const VERBOSE = args.includes('--verbose');

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function log(msg: string): void {
  console.log(msg);
}

function verbose(msg: string): void {
  if (VERBOSE) console.log(`  [verbose] ${msg}`);
}

interface ExerciseEntry {
  id: string;
  lessonDir: string;
  filename: string;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function main(): void {
  log('=== Content Registry Generator ===\n');

  // 1. Discover lesson directories
  if (!existsSync(EXERCISES_DIR)) {
    console.error(`ERROR: Exercises directory not found: ${EXERCISES_DIR}`);
    process.exit(1);
  }

  const lessonDirs = readdirSync(EXERCISES_DIR, { withFileTypes: true })
    .filter((d) => d.isDirectory() && d.name.startsWith('lesson-'))
    .map((d) => d.name)
    .sort();

  log(`Found ${lessonDirs.length} lesson directories: ${lessonDirs.join(', ')}`);

  // 2. Scan each lesson directory for exercise JSON files
  const entries: ExerciseEntry[] = [];
  const seenIds = new Set<string>();
  const errors: string[] = [];

  for (const lessonDir of lessonDirs) {
    const dirPath = join(EXERCISES_DIR, lessonDir);
    const jsonFiles = readdirSync(dirPath)
      .filter((f) => f.endsWith('.json'))
      .sort();

    for (const filename of jsonFiles) {
      const filePath = join(dirPath, filename);
      try {
        const raw = readFileSync(filePath, 'utf-8');
        const exercise = JSON.parse(raw);

        if (!exercise.id) {
          errors.push(`${filePath}: missing 'id' field — skipping`);
          continue;
        }

        if (seenIds.has(exercise.id)) {
          errors.push(`Duplicate exercise ID: "${exercise.id}" in ${filePath} — skipping`);
          continue;
        }

        seenIds.add(exercise.id);
        entries.push({
          id: exercise.id,
          lessonDir,
          filename,
        });

        verbose(`${exercise.id} <- ${lessonDir}/${filename}`);
      } catch (e) {
        errors.push(`Failed to parse ${filePath}: ${e}`);
      }
    }
  }

  // 3. Sort entries alphabetically by ID
  entries.sort((a, b) => a.id.localeCompare(b.id));

  log(`\nDiscovered ${entries.length} exercises`);

  if (errors.length > 0) {
    log(`\nWARNINGS (${errors.length}):`);
    for (const err of errors) {
      log(`  - ${err}`);
    }
  }

  // 4. Generate TypeScript output
  const now = new Date().toISOString();

  const loaderLines = entries.map((entry) => {
    const requirePath = `${REQUIRE_PREFIX}/${entry.lessonDir}/${entry.filename}`;
    return `  '${entry.id}': () => require('${requirePath}') as Exercise,`;
  });

  const output = `/**
 * AUTO-GENERATED by scripts/generate-content-registry.ts
 * Do not edit manually. Run: npx tsx scripts/generate-content-registry.ts
 * Generated: ${now}
 * Exercises: ${entries.length}
 */

import type { Exercise } from '../core/exercises/types';

type ExerciseLoader = () => Exercise;

const EXERCISE_LOADERS: Record<string, ExerciseLoader> = {
${loaderLines.join('\n')}
};

/**
 * Load an exercise by ID. Returns null if not found.
 * The require() is deferred until this function is called (lazy loading).
 */
export function loadExerciseFromRegistry(id: string): Exercise | null {
  const loader = EXERCISE_LOADERS[id];
  return loader ? loader() : null;
}

/** Get all registered exercise IDs */
export function getRegisteredExerciseIds(): string[] {
  return Object.keys(EXERCISE_LOADERS);
}

/** Total number of registered exercises */
export const REGISTERED_EXERCISE_COUNT = ${entries.length};
`;

  // 5. Write or preview
  if (DRY_RUN) {
    log(`\n[dry-run] Would write ${output.length} bytes to ${OUTPUT_PATH}`);
    log(`\nGenerated file preview:\n`);
    log(output);
  } else {
    writeFileSync(OUTPUT_PATH, output, 'utf-8');
    log(`\nWrote ${OUTPUT_PATH} (${output.length} bytes)`);
  }

  log('Done.');
}

main();
